# This file is generated by the gen-stdlib script, do not edit it by hand

rtscript=$(STDLIB)/rt/hare.sc
# rt
stdlib_rt_srcs= \
	$(STDLIB)/rt/$(PLATFORM)/abort.ha \
	$(STDLIB)/rt/$(PLATFORM)/env.ha \
	$(STDLIB)/rt/$(PLATFORM)/errno.ha \
	$(STDLIB)/rt/$(PLATFORM)/types.ha \
	$(STDLIB)/rt/$(PLATFORM)/segmalloc.ha \
	$(STDLIB)/rt/$(PLATFORM)/platformstart.ha \
	$(STDLIB)/rt/$(PLATFORM)/prctl.ha \
	$(STDLIB)/rt/$(PLATFORM)/$(ARCH).ha \
	$(STDLIB)/rt/$(PLATFORM)/syscallno$(ARCH).ha \
	$(STDLIB)/rt/$(PLATFORM)/syscalls.ha \
	$(STDLIB)/rt/$(PLATFORM)/signal.ha \
	$(STDLIB)/rt/$(PLATFORM)/stat.ha \
	$(STDLIB)/rt/$(PLATFORM)/socket.ha \
	$(STDLIB)/rt/$(ARCH)/jmp.ha \
	$(STDLIB)/rt/$(ARCH)/backtrace.ha \
	$(STDLIB)/rt/ensure.ha \
	$(STDLIB)/rt/jmp.ha \
	$(STDLIB)/rt/malloc.ha \
	$(STDLIB)/rt/memcpy.ha \
	$(STDLIB)/rt/memmove.ha \
	$(STDLIB)/rt/memset.ha \
	$(STDLIB)/rt/strcmp.ha \
	$(STDLIB)/rt/abort.ha \
	$(STDLIB)/rt/start.ha

$(HARECACHE)/rt/rt.ssa: $(stdlib_rt_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/rt
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nrt \
		-t$(HARECACHE)/rt/rt.td $(stdlib_rt_srcs)

$(HARECACHE)/rt/start.o: $(STDLIB)/rt/$(PLATFORM)/start$(ARCH).s
	@printf 'AS \t$@\n'
	@mkdir -p $(HARECACHE)/rt
	@$(AS) -o $@ $<

stdlib_asm=$(HARECACHE)/rt/syscall.o \
	$(HARECACHE)/rt/setjmp.o \
	$(HARECACHE)/rt/longjmp.o \
	$(HARECACHE)/rt/restore.o \
	$(HARECACHE)/rt/getfp.o \
	$(HARECACHE)/rt/start.o

$(HARECACHE)/rt/syscall.o: $(STDLIB)/rt/$(PLATFORM)/syscall$(ARCH).s
	@printf 'AS \t$@\n'
	@mkdir -p $(HARECACHE)/rt
	@$(AS) -o $@ $<

$(HARECACHE)/rt/setjmp.o: $(STDLIB)/rt/$(ARCH)/setjmp.s
	@printf 'AS \t$@\n'
	@mkdir -p $(HARECACHE)/rt
	@$(AS) -o $@ $<

$(HARECACHE)/rt/longjmp.o: $(STDLIB)/rt/$(ARCH)/longjmp.s
	@printf 'AS \t$@\n'
	@mkdir -p $(HARECACHE)/rt
	@$(AS) -o $@ $<

$(HARECACHE)/rt/restore.o: $(STDLIB)/rt/$(ARCH)/restore.s
	@printf 'AS \t$@\n'
	@mkdir -p $(HARECACHE)/rt
	@$(AS) -o $@ $<

$(HARECACHE)/rt/getfp.o: $(STDLIB)/rt/$(ARCH)/getfp.s
	@printf 'AS \t$@\n'
	@mkdir -p $(HARECACHE)/rt
	@$(AS) -o $@ $<

$(HARECACHE)/rt/rt.a: $(HARECACHE)/rt/rt.o $(stdlib_asm)
	@printf 'AR\t$@\n'
	@$(AR) -csr $@ $(HARECACHE)/rt/rt.o $(stdlib_asm)

stdlib_rt=$(HARECACHE)/rt/rt.a
hare_stdlib_deps+=$(stdlib_rt)

# gen_lib ascii
stdlib_ascii=$(HARECACHE)/ascii/ascii.o
hare_stdlib_deps+=$(stdlib_ascii)

# gen_lib bufio
stdlib_bufio=$(HARECACHE)/bufio/bufio.o
hare_stdlib_deps+=$(stdlib_bufio)

# gen_lib bytes
stdlib_bytes=$(HARECACHE)/bytes/bytes.o
hare_stdlib_deps+=$(stdlib_bytes)

# gen_lib compress::flate
stdlib_compress_flate=$(HARECACHE)/compress/flate/compress_flate.o
hare_stdlib_deps+=$(stdlib_compress_flate)

# gen_lib compress::zlib
stdlib_compress_zlib=$(HARECACHE)/compress/zlib/compress_zlib.o
hare_stdlib_deps+=$(stdlib_compress_zlib)

# gen_lib crypto::blake2b
stdlib_crypto_blake2b=$(HARECACHE)/crypto/blake2b/crypto_blake2b.o
hare_stdlib_deps+=$(stdlib_crypto_blake2b)

# gen_lib crypto::math
stdlib_crypto_math=$(HARECACHE)/crypto/math/crypto_math.o
hare_stdlib_deps+=$(stdlib_crypto_math)

# gen_lib crypto::random
stdlib_crypto_random=$(HARECACHE)/crypto/random/crypto_random.o
hare_stdlib_deps+=$(stdlib_crypto_random)

# gen_lib crypto::md5
stdlib_crypto_md5=$(HARECACHE)/crypto/md5/crypto_md5.o
hare_stdlib_deps+=$(stdlib_crypto_md5)

# gen_lib crypto::sha1
stdlib_crypto_sha1=$(HARECACHE)/crypto/sha1/crypto_sha1.o
hare_stdlib_deps+=$(stdlib_crypto_sha1)

# gen_lib crypto::sha256
stdlib_crypto_sha256=$(HARECACHE)/crypto/sha256/crypto_sha256.o
hare_stdlib_deps+=$(stdlib_crypto_sha256)

# gen_lib crypto::sha512
stdlib_crypto_sha512=$(HARECACHE)/crypto/sha512/crypto_sha512.o
hare_stdlib_deps+=$(stdlib_crypto_sha512)

# gen_lib dirs
stdlib_dirs=$(HARECACHE)/dirs/dirs.o
hare_stdlib_deps+=$(stdlib_dirs)

# gen_lib encoding::base64
stdlib_encoding_base64=$(HARECACHE)/encoding/base64/encoding_base64.o
hare_stdlib_deps+=$(stdlib_encoding_base64)

# gen_lib encoding::hex
stdlib_encoding_hex=$(HARECACHE)/encoding/hex/encoding_hex.o
hare_stdlib_deps+=$(stdlib_encoding_hex)

# gen_lib encoding::utf8
stdlib_encoding_utf8=$(HARECACHE)/encoding/utf8/encoding_utf8.o
hare_stdlib_deps+=$(stdlib_encoding_utf8)

# gen_lib endian
stdlib_endian=$(HARECACHE)/endian/endian.o
hare_stdlib_deps+=$(stdlib_endian)

# gen_lib errors
stdlib_errors=$(HARECACHE)/errors/errors.o
hare_stdlib_deps+=$(stdlib_errors)

# gen_lib fmt
stdlib_fmt=$(HARECACHE)/fmt/fmt.o
hare_stdlib_deps+=$(stdlib_fmt)

# gen_lib format::elf
stdlib_format_elf=$(HARECACHE)/format/elf/format_elf.o
hare_stdlib_deps+=$(stdlib_format_elf)

# gen_lib format::xml
stdlib_format_xml=$(HARECACHE)/format/xml/format_xml.o
hare_stdlib_deps+=$(stdlib_format_xml)

# gen_lib fs
stdlib_fs=$(HARECACHE)/fs/fs.o
hare_stdlib_deps+=$(stdlib_fs)

# gen_lib fs::mem
stdlib_fs_mem=$(HARECACHE)/fs/mem/fs_mem.o
hare_stdlib_deps+=$(stdlib_fs_mem)

# gen_lib getopt
stdlib_getopt=$(HARECACHE)/getopt/getopt.o
hare_stdlib_deps+=$(stdlib_getopt)

# gen_lib hare::ast
stdlib_hare_ast=$(HARECACHE)/hare/ast/hare_ast.o
hare_stdlib_deps+=$(stdlib_hare_ast)

# gen_lib hare::lex
stdlib_hare_lex=$(HARECACHE)/hare/lex/hare_lex.o
hare_stdlib_deps+=$(stdlib_hare_lex)

# gen_lib hare::module
stdlib_hare_module=$(HARECACHE)/hare/module/hare_module.o
hare_stdlib_deps+=$(stdlib_hare_module)

# gen_lib hare::parse
stdlib_hare_parse=$(HARECACHE)/hare/parse/hare_parse.o
hare_stdlib_deps+=$(stdlib_hare_parse)

# gen_lib hare::types
stdlib_hare_types=$(HARECACHE)/hare/types/hare_types.o
hare_stdlib_deps+=$(stdlib_hare_types)

# gen_lib hare::unit
stdlib_hare_unit=$(HARECACHE)/hare/unit/hare_unit.o
hare_stdlib_deps+=$(stdlib_hare_unit)

# gen_lib hare::unparse
stdlib_hare_unparse=$(HARECACHE)/hare/unparse/hare_unparse.o
hare_stdlib_deps+=$(stdlib_hare_unparse)

# gen_lib hash
stdlib_hash=$(HARECACHE)/hash/hash.o
hare_stdlib_deps+=$(stdlib_hash)

# gen_lib hash::adler32
stdlib_hash_adler32=$(HARECACHE)/hash/adler32/hash_adler32.o
hare_stdlib_deps+=$(stdlib_hash_adler32)

# gen_lib hash::crc16
stdlib_hash_crc16=$(HARECACHE)/hash/crc16/hash_crc16.o
hare_stdlib_deps+=$(stdlib_hash_crc16)

# gen_lib hash::crc32
stdlib_hash_crc32=$(HARECACHE)/hash/crc32/hash_crc32.o
hare_stdlib_deps+=$(stdlib_hash_crc32)

# gen_lib hash::crc64
stdlib_hash_crc64=$(HARECACHE)/hash/crc64/hash_crc64.o
hare_stdlib_deps+=$(stdlib_hash_crc64)

# gen_lib hash::fnv
stdlib_hash_fnv=$(HARECACHE)/hash/fnv/hash_fnv.o
hare_stdlib_deps+=$(stdlib_hash_fnv)

# gen_lib io
stdlib_io=$(HARECACHE)/io/io.o
hare_stdlib_deps+=$(stdlib_io)

# gen_lib linux
stdlib_linux=$(HARECACHE)/linux/linux.o
hare_stdlib_deps+=$(stdlib_linux)

# gen_lib linux::signalfd
stdlib_linux_signalfd=$(HARECACHE)/linux/signalfd/linux_signalfd.o
hare_stdlib_deps+=$(stdlib_linux_signalfd)

# gen_lib linux::io_uring
stdlib_linux_io_uring=$(HARECACHE)/linux/io_uring/linux_io_uring.o
hare_stdlib_deps+=$(stdlib_linux_io_uring)

# gen_lib linux::vdso
stdlib_linux_vdso=$(HARECACHE)/linux/vdso/linux_vdso.o
hare_stdlib_deps+=$(stdlib_linux_vdso)

# gen_lib math
stdlib_math=$(HARECACHE)/math/math.o
hare_stdlib_deps+=$(stdlib_math)

# gen_lib net
stdlib_net=$(HARECACHE)/net/net.o
hare_stdlib_deps+=$(stdlib_net)

# gen_lib net::dial
stdlib_net_dial=$(HARECACHE)/net/dial/net_dial.o
hare_stdlib_deps+=$(stdlib_net_dial)

# gen_lib net::dns
stdlib_net_dns=$(HARECACHE)/net/dns/net_dns.o
hare_stdlib_deps+=$(stdlib_net_dns)

# gen_lib net::ip
stdlib_net_ip=$(HARECACHE)/net/ip/net_ip.o
hare_stdlib_deps+=$(stdlib_net_ip)

# gen_lib net::tcp
stdlib_net_tcp=$(HARECACHE)/net/tcp/net_tcp.o
hare_stdlib_deps+=$(stdlib_net_tcp)

# gen_lib net::udp
stdlib_net_udp=$(HARECACHE)/net/udp/net_udp.o
hare_stdlib_deps+=$(stdlib_net_udp)

# gen_lib net::unix
stdlib_net_unix=$(HARECACHE)/net/unix/net_unix.o
hare_stdlib_deps+=$(stdlib_net_unix)

# gen_lib math::random
stdlib_math_random=$(HARECACHE)/math/random/math_random.o
hare_stdlib_deps+=$(stdlib_math_random)

# gen_lib os
stdlib_os=$(HARECACHE)/os/os.o
hare_stdlib_deps+=$(stdlib_os)

# gen_lib os::exec
stdlib_os_exec=$(HARECACHE)/os/exec/os_exec.o
hare_stdlib_deps+=$(stdlib_os_exec)

# gen_lib path
stdlib_path=$(HARECACHE)/path/path.o
hare_stdlib_deps+=$(stdlib_path)

# gen_lib slice
stdlib_slice=$(HARECACHE)/slice/slice.o
hare_stdlib_deps+=$(stdlib_slice)

# gen_lib sort
stdlib_sort=$(HARECACHE)/sort/sort.o
hare_stdlib_deps+=$(stdlib_sort)

# gen_lib strconv
stdlib_strconv=$(HARECACHE)/strconv/strconv.o
hare_stdlib_deps+=$(stdlib_strconv)

# gen_lib strings
stdlib_strings=$(HARECACHE)/strings/strings.o
hare_stdlib_deps+=$(stdlib_strings)

# gen_lib strio
stdlib_strio=$(HARECACHE)/strio/strio.o
hare_stdlib_deps+=$(stdlib_strio)

# gen_lib temp
stdlib_temp=$(HARECACHE)/temp/temp.o
hare_stdlib_deps+=$(stdlib_temp)

# gen_lib time
stdlib_time=$(HARECACHE)/time/time.o
hare_stdlib_deps+=$(stdlib_time)

# gen_lib types
stdlib_types=$(HARECACHE)/types/types.o
hare_stdlib_deps+=$(stdlib_types)

# gen_lib unicode
stdlib_unicode=$(HARECACHE)/unicode/unicode.o
hare_stdlib_deps+=$(stdlib_unicode)

# gen_lib unix
stdlib_unix=$(HARECACHE)/unix/unix.o
hare_stdlib_deps+=$(stdlib_unix)

# gen_lib unix::hosts
stdlib_unix_hosts=$(HARECACHE)/unix/hosts/unix_hosts.o
hare_stdlib_deps+=$(stdlib_unix_hosts)

# gen_lib unix::passwd
stdlib_unix_passwd=$(HARECACHE)/unix/passwd/unix_passwd.o
hare_stdlib_deps+=$(stdlib_unix_passwd)

# gen_lib unix::poll
stdlib_unix_poll=$(HARECACHE)/unix/poll/unix_poll.o
hare_stdlib_deps+=$(stdlib_unix_poll)

# gen_lib unix::resolvconf
stdlib_unix_resolvconf=$(HARECACHE)/unix/resolvconf/unix_resolvconf.o
hare_stdlib_deps+=$(stdlib_unix_resolvconf)

# gen_lib unix::tty
stdlib_unix_tty=$(HARECACHE)/unix/tty/unix_tty.o
hare_stdlib_deps+=$(stdlib_unix_tty)

# gen_lib uuid
stdlib_uuid=$(HARECACHE)/uuid/uuid.o
hare_stdlib_deps+=$(stdlib_uuid)

# ascii
stdlib_ascii_srcs= \
	$(STDLIB)/ascii/ctype.ha \
	$(STDLIB)/ascii/strcmp.ha

$(HARECACHE)/ascii/ascii.ssa: $(stdlib_ascii_srcs) $(stdlib_rt) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/ascii
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nascii \
		-t$(HARECACHE)/ascii/ascii.td $(stdlib_ascii_srcs)

# bufio
stdlib_bufio_srcs= \
	$(STDLIB)/bufio/buffered.ha \
	$(STDLIB)/bufio/memstream.ha \
	$(STDLIB)/bufio/scanner.ha

$(HARECACHE)/bufio/bufio.ssa: $(stdlib_bufio_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_bytes) $(stdlib_strings) $(stdlib_encoding_utf8) $(stdlib_errors) $(stdlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/bufio
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nbufio \
		-t$(HARECACHE)/bufio/bufio.td $(stdlib_bufio_srcs)

# bytes
stdlib_bytes_srcs= \
	$(STDLIB)/bytes/contains.ha \
	$(STDLIB)/bytes/copy.ha \
	$(STDLIB)/bytes/equal.ha \
	$(STDLIB)/bytes/index.ha \
	$(STDLIB)/bytes/reverse.ha \
	$(STDLIB)/bytes/tokenize.ha \
	$(STDLIB)/bytes/two_way.ha

$(HARECACHE)/bytes/bytes.ssa: $(stdlib_bytes_srcs) $(stdlib_rt) $(stdlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/bytes
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nbytes \
		-t$(HARECACHE)/bytes/bytes.td $(stdlib_bytes_srcs)

# compress::flate
stdlib_compress_flate_srcs= \
	$(STDLIB)/compress/flate/inflate.ha

$(HARECACHE)/compress/flate/compress_flate.ssa: $(stdlib_compress_flate_srcs) $(stdlib_rt) $(stdlib_bufio) $(stdlib_bytes) $(stdlib_endian) $(stdlib_errors) $(stdlib_io) $(stdlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/compress/flate
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ncompress::flate \
		-t$(HARECACHE)/compress/flate/compress_flate.td $(stdlib_compress_flate_srcs)

# compress::zlib
stdlib_compress_zlib_srcs= \
	$(STDLIB)/compress/zlib/reader.ha

$(HARECACHE)/compress/zlib/compress_zlib.ssa: $(stdlib_compress_zlib_srcs) $(stdlib_rt) $(stdlib_bufio) $(stdlib_bytes) $(stdlib_compress_flate) $(stdlib_endian) $(stdlib_errors) $(stdlib_hash) $(stdlib_hash_adler32) $(stdlib_io) $(stdlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/compress/zlib
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ncompress::zlib \
		-t$(HARECACHE)/compress/zlib/compress_zlib.td $(stdlib_compress_zlib_srcs)

# crypto::blake2b
stdlib_crypto_blake2b_srcs= \
	$(STDLIB)/crypto/blake2b/blake2b.ha

$(HARECACHE)/crypto/blake2b/crypto_blake2b.ssa: $(stdlib_crypto_blake2b_srcs) $(stdlib_rt) $(stdlib_encoding_hex) $(stdlib_fmt) $(stdlib_hash) $(stdlib_io) $(stdlib_strings) $(stdlib_strio) $(stdlib_crypto_math) $(stdlib_endian)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/crypto/blake2b
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ncrypto::blake2b \
		-t$(HARECACHE)/crypto/blake2b/crypto_blake2b.td $(stdlib_crypto_blake2b_srcs)

# crypto::math
stdlib_crypto_math_srcs= \
	$(STDLIB)/crypto/math/bits.ha

$(HARECACHE)/crypto/math/crypto_math.ssa: $(stdlib_crypto_math_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/crypto/math
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ncrypto::math \
		-t$(HARECACHE)/crypto/math/crypto_math.td $(stdlib_crypto_math_srcs)

# crypto::random
stdlib_crypto_random_srcs= \
	$(STDLIB)/crypto/random/$(PLATFORM).ha \
	$(STDLIB)/crypto/random/random.ha

$(HARECACHE)/crypto/random/crypto_random.ssa: $(stdlib_crypto_random_srcs) $(stdlib_rt) $(stdlib_rt) $(stdlib_io) $(stdlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/crypto/random
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ncrypto::random \
		-t$(HARECACHE)/crypto/random/crypto_random.td $(stdlib_crypto_random_srcs)

# crypto::md5
stdlib_crypto_md5_srcs= \
	$(STDLIB)/crypto/md5/md5.ha

$(HARECACHE)/crypto/md5/crypto_md5.ssa: $(stdlib_crypto_md5_srcs) $(stdlib_rt) $(stdlib_hash) $(stdlib_io) $(stdlib_endian)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/crypto/md5
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ncrypto::md5 \
		-t$(HARECACHE)/crypto/md5/crypto_md5.td $(stdlib_crypto_md5_srcs)

# crypto::sha1
stdlib_crypto_sha1_srcs= \
	$(STDLIB)/crypto/sha1/sha1.ha

$(HARECACHE)/crypto/sha1/crypto_sha1.ssa: $(stdlib_crypto_sha1_srcs) $(stdlib_rt) $(stdlib_hash) $(stdlib_io) $(stdlib_endian)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/crypto/sha1
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ncrypto::sha1 \
		-t$(HARECACHE)/crypto/sha1/crypto_sha1.td $(stdlib_crypto_sha1_srcs)

# crypto::sha256
stdlib_crypto_sha256_srcs= \
	$(STDLIB)/crypto/sha256/sha256.ha

$(HARECACHE)/crypto/sha256/crypto_sha256.ssa: $(stdlib_crypto_sha256_srcs) $(stdlib_rt) $(stdlib_hash) $(stdlib_io) $(stdlib_endian)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/crypto/sha256
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ncrypto::sha256 \
		-t$(HARECACHE)/crypto/sha256/crypto_sha256.td $(stdlib_crypto_sha256_srcs)

# crypto::sha512
stdlib_crypto_sha512_srcs= \
	$(STDLIB)/crypto/sha512/sha512.ha

$(HARECACHE)/crypto/sha512/crypto_sha512.ssa: $(stdlib_crypto_sha512_srcs) $(stdlib_rt) $(stdlib_hash) $(stdlib_io) $(stdlib_endian)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/crypto/sha512
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ncrypto::sha512 \
		-t$(HARECACHE)/crypto/sha512/crypto_sha512.td $(stdlib_crypto_sha512_srcs)

# dirs
stdlib_dirs_srcs= \
	$(STDLIB)/dirs/xdg.ha

$(HARECACHE)/dirs/dirs.ssa: $(stdlib_dirs_srcs) $(stdlib_rt) $(stdlib_fs) $(stdlib_os) $(stdlib_path)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/dirs
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ndirs \
		-t$(HARECACHE)/dirs/dirs.td $(stdlib_dirs_srcs)

# encoding::base64
stdlib_encoding_base64_srcs= \
	$(STDLIB)/encoding/base64/base64.ha

$(HARECACHE)/encoding/base64/encoding_base64.ssa: $(stdlib_encoding_base64_srcs) $(stdlib_rt) $(stdlib_bufio) $(stdlib_bytes) $(stdlib_io) $(stdlib_strio) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/encoding/base64
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nencoding::base64 \
		-t$(HARECACHE)/encoding/base64/encoding_base64.td $(stdlib_encoding_base64_srcs)

# encoding::hex
stdlib_encoding_hex_srcs= \
	$(STDLIB)/encoding/hex/hex.ha

$(HARECACHE)/encoding/hex/encoding_hex.ssa: $(stdlib_encoding_hex_srcs) $(stdlib_rt) $(stdlib_ascii) $(stdlib_bytes) $(stdlib_fmt) $(stdlib_io) $(stdlib_strconv) $(stdlib_strio) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/encoding/hex
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nencoding::hex \
		-t$(HARECACHE)/encoding/hex/encoding_hex.td $(stdlib_encoding_hex_srcs)

# encoding::utf8
stdlib_encoding_utf8_srcs= \
	$(STDLIB)/encoding/utf8/decode.ha \
	$(STDLIB)/encoding/utf8/encode.ha \
	$(STDLIB)/encoding/utf8/rune.ha

$(HARECACHE)/encoding/utf8/encoding_utf8.ssa: $(stdlib_encoding_utf8_srcs) $(stdlib_rt) $(stdlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/encoding/utf8
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nencoding::utf8 \
		-t$(HARECACHE)/encoding/utf8/encoding_utf8.td $(stdlib_encoding_utf8_srcs)

# endian
stdlib_endian_srcs= \
	$(STDLIB)/endian/big.ha \
	$(STDLIB)/endian/network.ha \
	$(STDLIB)/endian/little.ha \
	$(STDLIB)/endian/endian.ha \
	$(STDLIB)/endian/host$(ARCH).ha

$(HARECACHE)/endian/endian.ssa: $(stdlib_endian_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/endian
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nendian \
		-t$(HARECACHE)/endian/endian.td $(stdlib_endian_srcs)

# errors
stdlib_errors_srcs= \
	$(STDLIB)/errors/common.ha \
	$(STDLIB)/errors/opaque.ha \
	$(STDLIB)/errors/string.ha \
	$(STDLIB)/errors/rt.ha

$(HARECACHE)/errors/errors.ssa: $(stdlib_errors_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/errors
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nerrors \
		-t$(HARECACHE)/errors/errors.td $(stdlib_errors_srcs)

# fmt
stdlib_fmt_srcs= \
	$(STDLIB)/fmt/fmt.ha

$(HARECACHE)/fmt/fmt.ssa: $(stdlib_fmt_srcs) $(stdlib_rt) $(stdlib_bufio) $(stdlib_io) $(stdlib_os) $(stdlib_strconv) $(stdlib_strings) $(stdlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/fmt
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nfmt \
		-t$(HARECACHE)/fmt/fmt.td $(stdlib_fmt_srcs)

# format::elf
stdlib_format_elf_srcs= \
	$(STDLIB)/format/elf/$(ARCH).ha \
	$(STDLIB)/format/elf/$(PLATFORM).ha \
	$(STDLIB)/format/elf/types.ha

$(HARECACHE)/format/elf/format_elf.ssa: $(stdlib_format_elf_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/format/elf
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nformat::elf \
		-t$(HARECACHE)/format/elf/format_elf.td $(stdlib_format_elf_srcs)

# format::xml
stdlib_format_xml_srcs= \
	$(STDLIB)/format/xml/types.ha \
	$(STDLIB)/format/xml/parser.ha \
	$(STDLIB)/format/xml/chars.ha

$(HARECACHE)/format/xml/format_xml.ssa: $(stdlib_format_xml_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_bufio) $(stdlib_strings) $(stdlib_ascii) $(stdlib_strio) $(stdlib_os)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/format/xml
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nformat::xml \
		-t$(HARECACHE)/format/xml/format_xml.td $(stdlib_format_xml_srcs)

# fs
stdlib_fs_srcs= \
	$(STDLIB)/fs/types.ha \
	$(STDLIB)/fs/fs.ha \
	$(STDLIB)/fs/util.ha

$(HARECACHE)/fs/fs.ssa: $(stdlib_fs_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_strings) $(stdlib_path) $(stdlib_time) $(stdlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/fs
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nfs \
		-t$(HARECACHE)/fs/fs.td $(stdlib_fs_srcs)

# fs::mem
stdlib_fs_mem_srcs= \
	$(STDLIB)/fs/mem/mem.ha \
	$(STDLIB)/fs/mem/stream.ha \
	$(STDLIB)/fs/mem/util.ha

$(HARECACHE)/fs/mem/fs_mem.ssa: $(stdlib_fs_mem_srcs) $(stdlib_rt) $(stdlib_bufio) $(stdlib_errors) $(stdlib_fs) $(stdlib_hash) $(stdlib_hash_fnv) $(stdlib_io) $(stdlib_path) $(stdlib_strconv) $(stdlib_strings) $(stdlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/fs/mem
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nfs::mem \
		-t$(HARECACHE)/fs/mem/fs_mem.td $(stdlib_fs_mem_srcs)

# getopt
stdlib_getopt_srcs= \
	$(STDLIB)/getopt/getopts.ha

$(HARECACHE)/getopt/getopt.ssa: $(stdlib_getopt_srcs) $(stdlib_rt) $(stdlib_encoding_utf8) $(stdlib_fmt) $(stdlib_io) $(stdlib_os) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/getopt
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ngetopt \
		-t$(HARECACHE)/getopt/getopt.td $(stdlib_getopt_srcs)

# hare::ast
stdlib_hare_ast_srcs= \
	$(STDLIB)/hare/ast/decl.ha \
	$(STDLIB)/hare/ast/expr.ha \
	$(STDLIB)/hare/ast/ident.ha \
	$(STDLIB)/hare/ast/import.ha \
	$(STDLIB)/hare/ast/type.ha \
	$(STDLIB)/hare/ast/unit.ha

$(HARECACHE)/hare/ast/hare_ast.ssa: $(stdlib_hare_ast_srcs) $(stdlib_rt) $(stdlib_hare_lex) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hare/ast
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhare::ast \
		-t$(HARECACHE)/hare/ast/hare_ast.td $(stdlib_hare_ast_srcs)

# hare::lex
stdlib_hare_lex_srcs= \
	$(STDLIB)/hare/lex/token.ha \
	$(STDLIB)/hare/lex/lex.ha

$(HARECACHE)/hare/lex/hare_lex.ssa: $(stdlib_hare_lex_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_bufio) $(stdlib_strings) $(stdlib_types) $(stdlib_fmt) $(stdlib_sort) $(stdlib_strio)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hare/lex
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhare::lex \
		-t$(HARECACHE)/hare/lex/hare_lex.td $(stdlib_hare_lex_srcs)

# hare::module
stdlib_hare_module_srcs= \
	$(STDLIB)/hare/module/types.ha \
	$(STDLIB)/hare/module/context.ha \
	$(STDLIB)/hare/module/scan.ha \
	$(STDLIB)/hare/module/manifest.ha

$(HARECACHE)/hare/module/hare_module.ssa: $(stdlib_hare_module_srcs) $(stdlib_rt) $(stdlib_hare_ast) $(stdlib_hare_lex) $(stdlib_hare_parse) $(stdlib_hare_unparse) $(stdlib_strio) $(stdlib_fs) $(stdlib_io) $(stdlib_strings) $(stdlib_hash) $(stdlib_crypto_sha256) $(stdlib_dirs) $(stdlib_bytes) $(stdlib_encoding_utf8) $(stdlib_ascii) $(stdlib_fmt) $(stdlib_time) $(stdlib_slice) $(stdlib_bufio) $(stdlib_strconv) $(stdlib_os) $(stdlib_encoding_hex) $(stdlib_sort) $(stdlib_errors) $(stdlib_temp)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hare/module
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhare::module \
		-t$(HARECACHE)/hare/module/hare_module.td $(stdlib_hare_module_srcs)

# hare::parse
stdlib_hare_parse_srcs= \
	$(STDLIB)/hare/parse/decl.ha \
	$(STDLIB)/hare/parse/expr.ha \
	$(STDLIB)/hare/parse/ident.ha \
	$(STDLIB)/hare/parse/import.ha \
	$(STDLIB)/hare/parse/parse.ha \
	$(STDLIB)/hare/parse/type.ha \
	$(STDLIB)/hare/parse/unit.ha

$(HARECACHE)/hare/parse/hare_parse.ssa: $(stdlib_hare_parse_srcs) $(stdlib_rt) $(stdlib_hare_ast) $(stdlib_hare_lex) $(stdlib_hare_unparse) $(stdlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hare/parse
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhare::parse \
		-t$(HARECACHE)/hare/parse/hare_parse.td $(stdlib_hare_parse_srcs)

# hare::types
stdlib_hare_types_srcs= \
	$(STDLIB)/hare/types/arch.ha \
	$(STDLIB)/hare/types/builtins.ha \
	$(STDLIB)/hare/types/class.ha \
	$(STDLIB)/hare/types/hash.ha \
	$(STDLIB)/hare/types/lookup.ha \
	$(STDLIB)/hare/types/store.ha \
	$(STDLIB)/hare/types/types.ha

$(HARECACHE)/hare/types/hare_types.ssa: $(stdlib_hare_types_srcs) $(stdlib_rt) $(stdlib_hare_ast) $(stdlib_hare_parse) $(stdlib_hash) $(stdlib_hash_fnv) $(stdlib_endian)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hare/types
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhare::types \
		-t$(HARECACHE)/hare/types/hare_types.td $(stdlib_hare_types_srcs)

# hare::unit
stdlib_hare_unit_srcs= \
	$(STDLIB)/hare/unit/check.ha \
	$(STDLIB)/hare/unit/context.ha \
	$(STDLIB)/hare/unit/errors.ha \
	$(STDLIB)/hare/unit/expr.ha \
	$(STDLIB)/hare/unit/process.ha \
	$(STDLIB)/hare/unit/scan.ha \
	$(STDLIB)/hare/unit/scope.ha \
	$(STDLIB)/hare/unit/unit.ha

$(HARECACHE)/hare/unit/hare_unit.ssa: $(stdlib_hare_unit_srcs) $(stdlib_rt) $(stdlib_hare_ast) $(stdlib_hare_types) $(stdlib_hash) $(stdlib_hash_fnv) $(stdlib_strings) $(stdlib_hare_lex) $(stdlib_bufio) $(stdlib_hare_parse)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hare/unit
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhare::unit \
		-t$(HARECACHE)/hare/unit/hare_unit.td $(stdlib_hare_unit_srcs)

# hare::unparse
stdlib_hare_unparse_srcs= \
	$(STDLIB)/hare/unparse/expr.ha \
	$(STDLIB)/hare/unparse/decl.ha \
	$(STDLIB)/hare/unparse/ident.ha \
	$(STDLIB)/hare/unparse/import.ha \
	$(STDLIB)/hare/unparse/type.ha \
	$(STDLIB)/hare/unparse/unit.ha \
	$(STDLIB)/hare/unparse/util.ha

$(HARECACHE)/hare/unparse/hare_unparse.ssa: $(stdlib_hare_unparse_srcs) $(stdlib_rt) $(stdlib_fmt) $(stdlib_io) $(stdlib_strio) $(stdlib_hare_ast)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hare/unparse
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhare::unparse \
		-t$(HARECACHE)/hare/unparse/hare_unparse.td $(stdlib_hare_unparse_srcs)

# hash
stdlib_hash_srcs= \
	$(STDLIB)/hash/hash.ha

$(HARECACHE)/hash/hash.ssa: $(stdlib_hash_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hash
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhash \
		-t$(HARECACHE)/hash/hash.td $(stdlib_hash_srcs)

# hash::adler32
stdlib_hash_adler32_srcs= \
	$(STDLIB)/hash/adler32/adler32.ha

$(HARECACHE)/hash/adler32/hash_adler32.ssa: $(stdlib_hash_adler32_srcs) $(stdlib_rt) $(stdlib_endian) $(stdlib_hash) $(stdlib_io) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hash/adler32
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhash::adler32 \
		-t$(HARECACHE)/hash/adler32/hash_adler32.td $(stdlib_hash_adler32_srcs)

# hash::crc16
stdlib_hash_crc16_srcs= \
	$(STDLIB)/hash/crc16/crc16.ha

$(HARECACHE)/hash/crc16/hash_crc16.ssa: $(stdlib_hash_crc16_srcs) $(stdlib_rt) $(stdlib_endian) $(stdlib_hash) $(stdlib_io) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hash/crc16
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhash::crc16 \
		-t$(HARECACHE)/hash/crc16/hash_crc16.td $(stdlib_hash_crc16_srcs)

# hash::crc32
stdlib_hash_crc32_srcs= \
	$(STDLIB)/hash/crc32/crc32.ha

$(HARECACHE)/hash/crc32/hash_crc32.ssa: $(stdlib_hash_crc32_srcs) $(stdlib_rt) $(stdlib_endian) $(stdlib_hash) $(stdlib_io) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hash/crc32
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhash::crc32 \
		-t$(HARECACHE)/hash/crc32/hash_crc32.td $(stdlib_hash_crc32_srcs)

# hash::crc64
stdlib_hash_crc64_srcs= \
	$(STDLIB)/hash/crc64/crc64.ha

$(HARECACHE)/hash/crc64/hash_crc64.ssa: $(stdlib_hash_crc64_srcs) $(stdlib_rt) $(stdlib_endian) $(stdlib_hash) $(stdlib_io) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hash/crc64
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhash::crc64 \
		-t$(HARECACHE)/hash/crc64/hash_crc64.td $(stdlib_hash_crc64_srcs)

# hash::fnv
stdlib_hash_fnv_srcs= \
	$(STDLIB)/hash/fnv/fnv.ha

$(HARECACHE)/hash/fnv/hash_fnv.ssa: $(stdlib_hash_fnv_srcs) $(stdlib_rt) $(stdlib_hash) $(stdlib_io) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hash/fnv
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhash::fnv \
		-t$(HARECACHE)/hash/fnv/hash_fnv.td $(stdlib_hash_fnv_srcs)

# io
stdlib_io_srcs= \
	$(STDLIB)/io/arch$(ARCH).ha \
	$(STDLIB)/io/copy.ha \
	$(STDLIB)/io/drain.ha \
	$(STDLIB)/io/limit.ha \
	$(STDLIB)/io/println$(PLATFORM).ha \
	$(STDLIB)/io/stream.ha \
	$(STDLIB)/io/tee.ha \
	$(STDLIB)/io/types.ha \
	$(STDLIB)/io/$(PLATFORM)/file.ha

$(HARECACHE)/io/io.ssa: $(stdlib_io_srcs) $(stdlib_rt) $(stdlib_strings) $(stdlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/io
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nio \
		-t$(HARECACHE)/io/io.td $(stdlib_io_srcs)

# linux
stdlib_linux_srcs= \
	$(STDLIB)/linux/start.ha \
	$(STDLIB)/linux/env.ha

$(HARECACHE)/linux/linux.ssa: $(stdlib_linux_srcs) $(stdlib_rt) $(stdlib_format_elf)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/linux
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nlinux \
		-t$(HARECACHE)/linux/linux.td $(stdlib_linux_srcs)

# linux::signalfd
stdlib_linux_signalfd_srcs= \
	$(STDLIB)/linux/signalfd/signalfd.ha

$(HARECACHE)/linux/signalfd/linux_signalfd.ssa: $(stdlib_linux_signalfd_srcs) $(stdlib_rt) $(stdlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/linux/signalfd
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nlinux::signalfd \
		-t$(HARECACHE)/linux/signalfd/linux_signalfd.td $(stdlib_linux_signalfd_srcs)

# linux::io_uring
stdlib_linux_io_uring_srcs= \
	$(STDLIB)/linux/io_uring/cqe.ha \
	$(STDLIB)/linux/io_uring/queue.ha \
	$(STDLIB)/linux/io_uring/register.ha \
	$(STDLIB)/linux/io_uring/setup.ha \
	$(STDLIB)/linux/io_uring/sqe.ha \
	$(STDLIB)/linux/io_uring/uring.ha

$(HARECACHE)/linux/io_uring/linux_io_uring.ssa: $(stdlib_linux_io_uring_srcs) $(stdlib_rt) $(stdlib_errors) $(stdlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/linux/io_uring
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nlinux::io_uring \
		-t$(HARECACHE)/linux/io_uring/linux_io_uring.td $(stdlib_linux_io_uring_srcs)

# linux::vdso
stdlib_linux_vdso_srcs= \
	$(STDLIB)/linux/vdso/vdso.ha

$(HARECACHE)/linux/vdso/linux_vdso.ssa: $(stdlib_linux_vdso_srcs) $(stdlib_rt) $(stdlib_linux) $(stdlib_strings) $(stdlib_format_elf)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/linux/vdso
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nlinux::vdso \
		-t$(HARECACHE)/linux/vdso/linux_vdso.td $(stdlib_linux_vdso_srcs)

# math
# math
stdlib_math_srcs= \
	$(STDLIB)/math/testdata.ha \
	$(STDLIB)/math/math.ha \
	$(STDLIB)/math/floats.ha \
	$(STDLIB)/math/ints.ha \
	$(STDLIB)/math/uints.ha \
	$(STDLIB)/math/trig.ha

$(HARECACHE)/math/math.ssa: $(stdlib_math_srcs) $(stdlib_rt) $(stdlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/math
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nmath \
		-t$(HARECACHE)/math/math.td $(stdlib_math_srcs)

# net
# net
stdlib_net_srcs= \
	$(STDLIB)/net/$(PLATFORM).ha \
	$(STDLIB)/net/errors.ha \
	$(STDLIB)/net/listener.ha

$(HARECACHE)/net/net.ssa: $(stdlib_net_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_os) $(stdlib_strings) $(stdlib_net_ip) $(stdlib_errors) $(stdlib_rt) $(stdlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/net
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nnet \
		-t$(HARECACHE)/net/net.td $(stdlib_net_srcs)

# net::dial
# net::dial
stdlib_net_dial_srcs= \
	$(STDLIB)/net/dial/registry.ha \
	$(STDLIB)/net/dial/dial.ha \
	$(STDLIB)/net/dial/ip.ha \
	$(STDLIB)/net/dial/resolve.ha

$(HARECACHE)/net/dial/net_dial.ssa: $(stdlib_net_dial_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_net) $(stdlib_net_ip) $(stdlib_net_tcp) $(stdlib_net_udp) $(stdlib_net_dns) $(stdlib_crypto_random) $(stdlib_strconv) $(stdlib_strings) $(stdlib_unix_hosts)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/net/dial
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nnet::dial \
		-t$(HARECACHE)/net/dial/net_dial.td $(stdlib_net_dial_srcs)

# net::dns
# net::dns
stdlib_net_dns_srcs= \
	$(STDLIB)/net/dns/decode.ha \
	$(STDLIB)/net/dns/error.ha \
	$(STDLIB)/net/dns/encode.ha \
	$(STDLIB)/net/dns/query.ha \
	$(STDLIB)/net/dns/types.ha

$(HARECACHE)/net/dns/net_dns.ssa: $(stdlib_net_dns_srcs) $(stdlib_rt) $(stdlib_ascii) $(stdlib_endian) $(stdlib_net) $(stdlib_net_udp) $(stdlib_net_ip) $(stdlib_fmt) $(stdlib_strings) $(stdlib_unix_resolvconf) $(stdlib_unix_poll) $(stdlib_rt) $(stdlib_time) $(stdlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/net/dns
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nnet::dns \
		-t$(HARECACHE)/net/dns/net_dns.td $(stdlib_net_dns_srcs)

# net::ip
stdlib_net_ip_srcs= \
	$(STDLIB)/net/ip/ip.ha \
	$(STDLIB)/net/ip/$(PLATFORM).ha

$(HARECACHE)/net/ip/net_ip.ssa: $(stdlib_net_ip_srcs) $(stdlib_rt) $(stdlib_bytes) $(stdlib_io) $(stdlib_strconv) $(stdlib_strings) $(stdlib_strio) $(stdlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/net/ip
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nnet::ip \
		-t$(HARECACHE)/net/ip/net_ip.td $(stdlib_net_ip_srcs)

# net::tcp
# net::tcp
stdlib_net_tcp_srcs= \
	$(STDLIB)/net/tcp/$(PLATFORM).ha \
	$(STDLIB)/net/tcp/listener.ha \
	$(STDLIB)/net/tcp/options.ha

$(HARECACHE)/net/tcp/net_tcp.ssa: $(stdlib_net_tcp_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_net) $(stdlib_net_ip) $(stdlib_os) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/net/tcp
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nnet::tcp \
		-t$(HARECACHE)/net/tcp/net_tcp.td $(stdlib_net_tcp_srcs)

# net::udp
# net::udp
stdlib_net_udp_srcs= \
	$(STDLIB)/net/udp/$(PLATFORM).ha \
	$(STDLIB)/net/udp/options.ha

$(HARECACHE)/net/udp/net_udp.ssa: $(stdlib_net_udp_srcs) $(stdlib_rt) $(stdlib_net) $(stdlib_net_ip) $(stdlib_errors) $(stdlib_rt) $(stdlib_os) $(stdlib_io)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/net/udp
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nnet::udp \
		-t$(HARECACHE)/net/udp/net_udp.td $(stdlib_net_udp_srcs)

# net::unix
# net::unix
stdlib_net_unix_srcs= \
	$(STDLIB)/net/unix/$(PLATFORM).ha \
	$(STDLIB)/net/unix/addr.ha \
	$(STDLIB)/net/unix/dial.ha \
	$(STDLIB)/net/unix/listener.ha \
	$(STDLIB)/net/unix/options.ha

$(HARECACHE)/net/unix/net_unix.ssa: $(stdlib_net_unix_srcs) $(stdlib_rt) $(stdlib_net) $(stdlib_errors) $(stdlib_os) $(stdlib_io) $(stdlib_strings) $(stdlib_types) $(stdlib_fmt) $(stdlib_net_dial)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/net/unix
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nnet::unix \
		-t$(HARECACHE)/net/unix/net_unix.td $(stdlib_net_unix_srcs)

# math::random
stdlib_math_random_srcs= \
	$(STDLIB)/math/random/random.ha

$(HARECACHE)/math/random/math_random.ssa: $(stdlib_math_random_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/math/random
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nmath::random \
		-t$(HARECACHE)/math/random/math_random.td $(stdlib_math_random_srcs)

# os
stdlib_os_srcs= \
	$(STDLIB)/os/$(PLATFORM)/environ.ha \
	$(STDLIB)/os/$(PLATFORM)/exit.ha \
	$(STDLIB)/os/$(PLATFORM)/dirfdfs.ha \
	$(STDLIB)/os/$(PLATFORM)/stdfd.ha \
	$(STDLIB)/os/$(PLATFORM)/fs.ha \
	$(STDLIB)/os/stdfd.ha \
	$(STDLIB)/os/fs.ha

$(HARECACHE)/os/os.ssa: $(stdlib_os_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_strings) $(stdlib_types) $(stdlib_fs) $(stdlib_encoding_utf8) $(stdlib_bytes) $(stdlib_bufio) $(stdlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/os
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nos \
		-t$(HARECACHE)/os/os.td $(stdlib_os_srcs)

# os::exec
stdlib_os_exec_srcs= \
	$(STDLIB)/os/exec/exec$(PLATFORM).ha \
	$(STDLIB)/os/exec/process$(PLATFORM).ha \
	$(STDLIB)/os/exec/types.ha \
	$(STDLIB)/os/exec/cmd.ha

$(HARECACHE)/os/exec/os_exec.ssa: $(stdlib_os_exec_srcs) $(stdlib_rt) $(stdlib_os) $(stdlib_strings) $(stdlib_fmt) $(stdlib_bytes) $(stdlib_path) $(stdlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/os/exec
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nos::exec \
		-t$(HARECACHE)/os/exec/os_exec.td $(stdlib_os_exec_srcs)

# path
stdlib_path_srcs= \
	$(STDLIB)/path/$(PLATFORM).ha \
	$(STDLIB)/path/util.ha \
	$(STDLIB)/path/join.ha \
	$(STDLIB)/path/names.ha \
	$(STDLIB)/path/iter.ha

$(HARECACHE)/path/path.ssa: $(stdlib_path_srcs) $(stdlib_rt) $(stdlib_strings) $(stdlib_bufio) $(stdlib_bytes)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/path
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Npath \
		-t$(HARECACHE)/path/path.td $(stdlib_path_srcs)

# slice
stdlib_slice_srcs= \
	$(STDLIB)/slice/reverse.ha \
	$(STDLIB)/slice/void.ha

$(HARECACHE)/slice/slice.ssa: $(stdlib_slice_srcs) $(stdlib_rt) $(stdlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/slice
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nslice \
		-t$(HARECACHE)/slice/slice.td $(stdlib_slice_srcs)

# sort
stdlib_sort_srcs= \
	$(STDLIB)/sort/search.ha \
	$(STDLIB)/sort/sort.ha

$(HARECACHE)/sort/sort.ssa: $(stdlib_sort_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/sort
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nsort \
		-t$(HARECACHE)/sort/sort.td $(stdlib_sort_srcs)

# strconv
stdlib_strconv_srcs= \
	$(STDLIB)/strconv/types.ha \
	$(STDLIB)/strconv/itos.ha \
	$(STDLIB)/strconv/utos.ha \
	$(STDLIB)/strconv/stou.ha \
	$(STDLIB)/strconv/stoi.ha \
	$(STDLIB)/strconv/numeric.ha \
	$(STDLIB)/strconv/ftos.ha \
	$(STDLIB)/strconv/stof.ha \
	$(STDLIB)/strconv/stof_data.ha

$(HARECACHE)/strconv/strconv.ssa: $(stdlib_strconv_srcs) $(stdlib_rt) $(stdlib_types) $(stdlib_strings) $(stdlib_ascii) $(stdlib_math)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/strconv
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nstrconv \
		-t$(HARECACHE)/strconv/strconv.td $(stdlib_strconv_srcs)

# strings
stdlib_strings_srcs= \
	$(STDLIB)/strings/concat.ha \
	$(STDLIB)/strings/contains.ha \
	$(STDLIB)/strings/cstrings.ha \
	$(STDLIB)/strings/dup.ha \
	$(STDLIB)/strings/iter.ha \
	$(STDLIB)/strings/sub.ha \
	$(STDLIB)/strings/suffix.ha \
	$(STDLIB)/strings/tokenize.ha \
	$(STDLIB)/strings/utf8.ha \
	$(STDLIB)/strings/index.ha \
	$(STDLIB)/strings/trim.ha

$(HARECACHE)/strings/strings.ssa: $(stdlib_strings_srcs) $(stdlib_rt) $(stdlib_bytes) $(stdlib_encoding_utf8) $(stdlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/strings
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nstrings \
		-t$(HARECACHE)/strings/strings.td $(stdlib_strings_srcs)

# strio
stdlib_strio_srcs= \
	$(STDLIB)/strio/dynamic.ha \
	$(STDLIB)/strio/fixed.ha \
	$(STDLIB)/strio/ops.ha

$(HARECACHE)/strio/strio.ssa: $(stdlib_strio_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_strings) $(stdlib_encoding_utf8) $(stdlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/strio
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nstrio \
		-t$(HARECACHE)/strio/strio.td $(stdlib_strio_srcs)

# temp
stdlib_temp_srcs= \
	$(STDLIB)/temp/$(PLATFORM).ha

$(HARECACHE)/temp/temp.ssa: $(stdlib_temp_srcs) $(stdlib_rt) $(stdlib_crypto_random) $(stdlib_encoding_hex) $(stdlib_fs) $(stdlib_io) $(stdlib_os) $(stdlib_path) $(stdlib_strio) $(stdlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/temp
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ntemp \
		-t$(HARECACHE)/temp/temp.td $(stdlib_temp_srcs)

# time
stdlib_time_srcs= \
	$(STDLIB)/time/$(PLATFORM)/functions.ha \
	$(STDLIB)/time/$(PLATFORM)/$(ARCH).ha \
	$(STDLIB)/time/arithm.ha \
	$(STDLIB)/time/types.ha

$(HARECACHE)/time/time.ssa: $(stdlib_time_srcs) $(stdlib_rt) $(stdlib_linux_vdso)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/time
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ntime \
		-t$(HARECACHE)/time/time.td $(stdlib_time_srcs)

# types
stdlib_types_srcs= \
	$(STDLIB)/types/limits.ha \
	$(STDLIB)/types/classes.ha \
	$(STDLIB)/types/arch$(ARCH).ha

$(HARECACHE)/types/types.ssa: $(stdlib_types_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/types
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ntypes \
		-t$(HARECACHE)/types/types.td $(stdlib_types_srcs)

# unicode
stdlib_unicode_srcs= \
	$(STDLIB)/unicode/properties.ha

$(HARECACHE)/unicode/unicode.ssa: $(stdlib_unicode_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/unicode
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nunicode \
		-t$(HARECACHE)/unicode/unicode.td $(stdlib_unicode_srcs)

# unix
stdlib_unix_srcs= \
	$(STDLIB)/unix/$(PLATFORM)/nice.ha \
	$(STDLIB)/unix/$(PLATFORM)/umask.ha \
	$(STDLIB)/unix/getuid.ha \
	$(STDLIB)/unix/setuid.ha

$(HARECACHE)/unix/unix.ssa: $(stdlib_unix_srcs) $(stdlib_rt) $(stdlib_errors) $(stdlib_fs)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/unix
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nunix \
		-t$(HARECACHE)/unix/unix.td $(stdlib_unix_srcs)

# unix::hosts
stdlib_unix_hosts_srcs= \
	$(STDLIB)/unix/hosts/lookup.ha

$(HARECACHE)/unix/hosts/unix_hosts.ssa: $(stdlib_unix_hosts_srcs) $(stdlib_rt) $(stdlib_os) $(stdlib_io) $(stdlib_bufio) $(stdlib_net_ip) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/unix/hosts
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nunix::hosts \
		-t$(HARECACHE)/unix/hosts/unix_hosts.td $(stdlib_unix_hosts_srcs)

# unix::passwd
stdlib_unix_passwd_srcs= \
	$(STDLIB)/unix/passwd/group.ha \
	$(STDLIB)/unix/passwd/passwd.ha \
	$(STDLIB)/unix/passwd/types.ha

$(HARECACHE)/unix/passwd/unix_passwd.ssa: $(stdlib_unix_passwd_srcs) $(stdlib_rt) $(stdlib_bufio) $(stdlib_io) $(stdlib_os) $(stdlib_strconv) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/unix/passwd
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nunix::passwd \
		-t$(HARECACHE)/unix/passwd/unix_passwd.td $(stdlib_unix_passwd_srcs)

# unix::poll
stdlib_unix_poll_srcs= \
	$(STDLIB)/unix/poll/$(PLATFORM).ha

$(HARECACHE)/unix/poll/unix_poll.ssa: $(stdlib_unix_poll_srcs) $(stdlib_rt) $(stdlib_rt) $(stdlib_errors) $(stdlib_time)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/unix/poll
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nunix::poll \
		-t$(HARECACHE)/unix/poll/unix_poll.td $(stdlib_unix_poll_srcs)

# unix::resolvconf
stdlib_unix_resolvconf_srcs= \
	$(STDLIB)/unix/resolvconf/load.ha

$(HARECACHE)/unix/resolvconf/unix_resolvconf.ssa: $(stdlib_unix_resolvconf_srcs) $(stdlib_rt) $(stdlib_os) $(stdlib_io) $(stdlib_bufio) $(stdlib_net_ip) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/unix/resolvconf
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nunix::resolvconf \
		-t$(HARECACHE)/unix/resolvconf/unix_resolvconf.td $(stdlib_unix_resolvconf_srcs)

# unix::tty
stdlib_unix_tty_srcs= \
	$(STDLIB)/unix/tty/types.ha \
	$(STDLIB)/unix/tty/$(PLATFORM)/isatty.ha \
	$(STDLIB)/unix/tty/$(PLATFORM)/open.ha \
	$(STDLIB)/unix/tty/$(PLATFORM)/winsize.ha

$(HARECACHE)/unix/tty/unix_tty.ssa: $(stdlib_unix_tty_srcs) $(stdlib_rt) $(stdlib_rt) $(stdlib_fs) $(stdlib_io) $(stdlib_os)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/unix/tty
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nunix::tty \
		-t$(HARECACHE)/unix/tty/unix_tty.td $(stdlib_unix_tty_srcs)

# uuid
stdlib_uuid_srcs= \
	$(STDLIB)/uuid/uuid.ha

$(HARECACHE)/uuid/uuid.ssa: $(stdlib_uuid_srcs) $(stdlib_rt) $(stdlib_crypto_random) $(stdlib_strio) $(stdlib_fmt) $(stdlib_endian) $(stdlib_io) $(stdlib_bytes) $(stdlib_bufio) $(stdlib_strings) $(stdlib_strconv)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/uuid
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nuuid \
		-t$(HARECACHE)/uuid/uuid.td $(stdlib_uuid_srcs)

# rt
testlib_rt_srcs= \
	$(STDLIB)/rt/$(PLATFORM)/abort.ha \
	$(STDLIB)/rt/$(PLATFORM)/env.ha \
	$(STDLIB)/rt/$(PLATFORM)/errno.ha \
	$(STDLIB)/rt/$(PLATFORM)/types.ha \
	$(STDLIB)/rt/$(PLATFORM)/segmalloc.ha \
	$(STDLIB)/rt/$(PLATFORM)/platformstart.ha \
	$(STDLIB)/rt/$(PLATFORM)/prctl.ha \
	$(STDLIB)/rt/$(PLATFORM)/$(ARCH).ha \
	$(STDLIB)/rt/$(PLATFORM)/syscallno$(ARCH).ha \
	$(STDLIB)/rt/$(PLATFORM)/syscalls.ha \
	$(STDLIB)/rt/$(PLATFORM)/signal.ha \
	$(STDLIB)/rt/$(PLATFORM)/stat.ha \
	$(STDLIB)/rt/$(PLATFORM)/socket.ha \
	$(STDLIB)/rt/$(ARCH)/jmp.ha \
	$(STDLIB)/rt/$(ARCH)/backtrace.ha \
	$(STDLIB)/rt/ensure.ha \
	$(STDLIB)/rt/jmp.ha \
	$(STDLIB)/rt/malloc.ha \
	$(STDLIB)/rt/memcpy.ha \
	$(STDLIB)/rt/memmove.ha \
	$(STDLIB)/rt/memset.ha \
	$(STDLIB)/rt/strcmp.ha \
	$(STDLIB)/rt/start+test.ha \
	$(STDLIB)/rt/abort+test.ha \
	$(STDLIB)/rt/+test/$(PLATFORM).ha \
	$(STDLIB)/rt/+test/cstring.ha \
	$(STDLIB)/rt/+test/run.ha \
	$(STDLIB)/rt/+test/ztos.ha

$(TESTCACHE)/rt/rt.ssa: $(testlib_rt_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/rt
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nrt \
		-t$(TESTCACHE)/rt/rt.td $(testlib_rt_srcs)

$(TESTCACHE)/rt/start.o: $(STDLIB)/rt/$(PLATFORM)/start$(ARCH).s
	@printf 'AS \t$@\n'
	@mkdir -p $(TESTCACHE)/rt
	@$(AS) -o $@ $<

testlib_asm=$(TESTCACHE)/rt/syscall.o \
	$(TESTCACHE)/rt/setjmp.o \
	$(TESTCACHE)/rt/longjmp.o \
	$(TESTCACHE)/rt/restore.o \
	$(TESTCACHE)/rt/getfp.o \
	$(TESTCACHE)/rt/start.o

$(TESTCACHE)/rt/syscall.o: $(STDLIB)/rt/$(PLATFORM)/syscall$(ARCH).s
	@printf 'AS \t$@\n'
	@mkdir -p $(TESTCACHE)/rt
	@$(AS) -o $@ $<

$(TESTCACHE)/rt/setjmp.o: $(STDLIB)/rt/$(ARCH)/setjmp.s
	@printf 'AS \t$@\n'
	@mkdir -p $(TESTCACHE)/rt
	@$(AS) -o $@ $<

$(TESTCACHE)/rt/longjmp.o: $(STDLIB)/rt/$(ARCH)/longjmp.s
	@printf 'AS \t$@\n'
	@mkdir -p $(TESTCACHE)/rt
	@$(AS) -o $@ $<

$(TESTCACHE)/rt/restore.o: $(STDLIB)/rt/$(ARCH)/restore.s
	@printf 'AS \t$@\n'
	@mkdir -p $(TESTCACHE)/rt
	@$(AS) -o $@ $<

$(TESTCACHE)/rt/getfp.o: $(STDLIB)/rt/$(ARCH)/getfp.s
	@printf 'AS \t$@\n'
	@mkdir -p $(TESTCACHE)/rt
	@$(AS) -o $@ $<

$(TESTCACHE)/rt/rt.a: $(TESTCACHE)/rt/rt.o $(testlib_asm)
	@printf 'AR\t$@\n'
	@$(AR) -csr $@ $(TESTCACHE)/rt/rt.o $(testlib_asm)

testlib_rt=$(TESTCACHE)/rt/rt.a
hare_testlib_deps+=$(testlib_rt)

# gen_lib ascii
testlib_ascii=$(TESTCACHE)/ascii/ascii.o
hare_testlib_deps+=$(testlib_ascii)

# gen_lib bufio
testlib_bufio=$(TESTCACHE)/bufio/bufio.o
hare_testlib_deps+=$(testlib_bufio)

# gen_lib bytes
testlib_bytes=$(TESTCACHE)/bytes/bytes.o
hare_testlib_deps+=$(testlib_bytes)

# gen_lib compress::flate
testlib_compress_flate=$(TESTCACHE)/compress/flate/compress_flate.o
hare_testlib_deps+=$(testlib_compress_flate)

# gen_lib compress::zlib
testlib_compress_zlib=$(TESTCACHE)/compress/zlib/compress_zlib.o
hare_testlib_deps+=$(testlib_compress_zlib)

# gen_lib crypto::blake2b
testlib_crypto_blake2b=$(TESTCACHE)/crypto/blake2b/crypto_blake2b.o
hare_testlib_deps+=$(testlib_crypto_blake2b)

# gen_lib crypto::math
testlib_crypto_math=$(TESTCACHE)/crypto/math/crypto_math.o
hare_testlib_deps+=$(testlib_crypto_math)

# gen_lib crypto::random
testlib_crypto_random=$(TESTCACHE)/crypto/random/crypto_random.o
hare_testlib_deps+=$(testlib_crypto_random)

# gen_lib crypto::md5
testlib_crypto_md5=$(TESTCACHE)/crypto/md5/crypto_md5.o
hare_testlib_deps+=$(testlib_crypto_md5)

# gen_lib crypto::sha1
testlib_crypto_sha1=$(TESTCACHE)/crypto/sha1/crypto_sha1.o
hare_testlib_deps+=$(testlib_crypto_sha1)

# gen_lib crypto::sha256
testlib_crypto_sha256=$(TESTCACHE)/crypto/sha256/crypto_sha256.o
hare_testlib_deps+=$(testlib_crypto_sha256)

# gen_lib crypto::sha512
testlib_crypto_sha512=$(TESTCACHE)/crypto/sha512/crypto_sha512.o
hare_testlib_deps+=$(testlib_crypto_sha512)

# gen_lib dirs
testlib_dirs=$(TESTCACHE)/dirs/dirs.o
hare_testlib_deps+=$(testlib_dirs)

# gen_lib encoding::base64
testlib_encoding_base64=$(TESTCACHE)/encoding/base64/encoding_base64.o
hare_testlib_deps+=$(testlib_encoding_base64)

# gen_lib encoding::hex
testlib_encoding_hex=$(TESTCACHE)/encoding/hex/encoding_hex.o
hare_testlib_deps+=$(testlib_encoding_hex)

# gen_lib encoding::utf8
testlib_encoding_utf8=$(TESTCACHE)/encoding/utf8/encoding_utf8.o
hare_testlib_deps+=$(testlib_encoding_utf8)

# gen_lib endian
testlib_endian=$(TESTCACHE)/endian/endian.o
hare_testlib_deps+=$(testlib_endian)

# gen_lib errors
testlib_errors=$(TESTCACHE)/errors/errors.o
hare_testlib_deps+=$(testlib_errors)

# gen_lib fmt
testlib_fmt=$(TESTCACHE)/fmt/fmt.o
hare_testlib_deps+=$(testlib_fmt)

# gen_lib format::elf
testlib_format_elf=$(TESTCACHE)/format/elf/format_elf.o
hare_testlib_deps+=$(testlib_format_elf)

# gen_lib format::xml
testlib_format_xml=$(TESTCACHE)/format/xml/format_xml.o
hare_testlib_deps+=$(testlib_format_xml)

# gen_lib fs
testlib_fs=$(TESTCACHE)/fs/fs.o
hare_testlib_deps+=$(testlib_fs)

# gen_lib fs::mem
testlib_fs_mem=$(TESTCACHE)/fs/mem/fs_mem.o
hare_testlib_deps+=$(testlib_fs_mem)

# gen_lib getopt
testlib_getopt=$(TESTCACHE)/getopt/getopt.o
hare_testlib_deps+=$(testlib_getopt)

# gen_lib hare::ast
testlib_hare_ast=$(TESTCACHE)/hare/ast/hare_ast.o
hare_testlib_deps+=$(testlib_hare_ast)

# gen_lib hare::lex
testlib_hare_lex=$(TESTCACHE)/hare/lex/hare_lex.o
hare_testlib_deps+=$(testlib_hare_lex)

# gen_lib hare::module
testlib_hare_module=$(TESTCACHE)/hare/module/hare_module.o
hare_testlib_deps+=$(testlib_hare_module)

# gen_lib hare::parse
testlib_hare_parse=$(TESTCACHE)/hare/parse/hare_parse.o
hare_testlib_deps+=$(testlib_hare_parse)

# gen_lib hare::types
testlib_hare_types=$(TESTCACHE)/hare/types/hare_types.o
hare_testlib_deps+=$(testlib_hare_types)

# gen_lib hare::unit
testlib_hare_unit=$(TESTCACHE)/hare/unit/hare_unit.o
hare_testlib_deps+=$(testlib_hare_unit)

# gen_lib hare::unparse
testlib_hare_unparse=$(TESTCACHE)/hare/unparse/hare_unparse.o
hare_testlib_deps+=$(testlib_hare_unparse)

# gen_lib hash
testlib_hash=$(TESTCACHE)/hash/hash.o
hare_testlib_deps+=$(testlib_hash)

# gen_lib hash::adler32
testlib_hash_adler32=$(TESTCACHE)/hash/adler32/hash_adler32.o
hare_testlib_deps+=$(testlib_hash_adler32)

# gen_lib hash::crc16
testlib_hash_crc16=$(TESTCACHE)/hash/crc16/hash_crc16.o
hare_testlib_deps+=$(testlib_hash_crc16)

# gen_lib hash::crc32
testlib_hash_crc32=$(TESTCACHE)/hash/crc32/hash_crc32.o
hare_testlib_deps+=$(testlib_hash_crc32)

# gen_lib hash::crc64
testlib_hash_crc64=$(TESTCACHE)/hash/crc64/hash_crc64.o
hare_testlib_deps+=$(testlib_hash_crc64)

# gen_lib hash::fnv
testlib_hash_fnv=$(TESTCACHE)/hash/fnv/hash_fnv.o
hare_testlib_deps+=$(testlib_hash_fnv)

# gen_lib io
testlib_io=$(TESTCACHE)/io/io.o
hare_testlib_deps+=$(testlib_io)

# gen_lib linux
testlib_linux=$(TESTCACHE)/linux/linux.o
hare_testlib_deps+=$(testlib_linux)

# gen_lib linux::signalfd
testlib_linux_signalfd=$(TESTCACHE)/linux/signalfd/linux_signalfd.o
hare_testlib_deps+=$(testlib_linux_signalfd)

# gen_lib linux::io_uring
testlib_linux_io_uring=$(TESTCACHE)/linux/io_uring/linux_io_uring.o
hare_testlib_deps+=$(testlib_linux_io_uring)

# gen_lib linux::vdso
testlib_linux_vdso=$(TESTCACHE)/linux/vdso/linux_vdso.o
hare_testlib_deps+=$(testlib_linux_vdso)

# gen_lib math
testlib_math=$(TESTCACHE)/math/math.o
hare_testlib_deps+=$(testlib_math)

# gen_lib net
testlib_net=$(TESTCACHE)/net/net.o
hare_testlib_deps+=$(testlib_net)

# gen_lib net::dial
testlib_net_dial=$(TESTCACHE)/net/dial/net_dial.o
hare_testlib_deps+=$(testlib_net_dial)

# gen_lib net::dns
testlib_net_dns=$(TESTCACHE)/net/dns/net_dns.o
hare_testlib_deps+=$(testlib_net_dns)

# gen_lib net::ip
testlib_net_ip=$(TESTCACHE)/net/ip/net_ip.o
hare_testlib_deps+=$(testlib_net_ip)

# gen_lib net::tcp
testlib_net_tcp=$(TESTCACHE)/net/tcp/net_tcp.o
hare_testlib_deps+=$(testlib_net_tcp)

# gen_lib net::udp
testlib_net_udp=$(TESTCACHE)/net/udp/net_udp.o
hare_testlib_deps+=$(testlib_net_udp)

# gen_lib net::unix
testlib_net_unix=$(TESTCACHE)/net/unix/net_unix.o
hare_testlib_deps+=$(testlib_net_unix)

# gen_lib math::random
testlib_math_random=$(TESTCACHE)/math/random/math_random.o
hare_testlib_deps+=$(testlib_math_random)

# gen_lib os
testlib_os=$(TESTCACHE)/os/os.o
hare_testlib_deps+=$(testlib_os)

# gen_lib os::exec
testlib_os_exec=$(TESTCACHE)/os/exec/os_exec.o
hare_testlib_deps+=$(testlib_os_exec)

# gen_lib path
testlib_path=$(TESTCACHE)/path/path.o
hare_testlib_deps+=$(testlib_path)

# gen_lib slice
testlib_slice=$(TESTCACHE)/slice/slice.o
hare_testlib_deps+=$(testlib_slice)

# gen_lib sort
testlib_sort=$(TESTCACHE)/sort/sort.o
hare_testlib_deps+=$(testlib_sort)

# gen_lib strconv
testlib_strconv=$(TESTCACHE)/strconv/strconv.o
hare_testlib_deps+=$(testlib_strconv)

# gen_lib strings
testlib_strings=$(TESTCACHE)/strings/strings.o
hare_testlib_deps+=$(testlib_strings)

# gen_lib strio
testlib_strio=$(TESTCACHE)/strio/strio.o
hare_testlib_deps+=$(testlib_strio)

# gen_lib temp
testlib_temp=$(TESTCACHE)/temp/temp.o
hare_testlib_deps+=$(testlib_temp)

# gen_lib time
testlib_time=$(TESTCACHE)/time/time.o
hare_testlib_deps+=$(testlib_time)

# gen_lib types
testlib_types=$(TESTCACHE)/types/types.o
hare_testlib_deps+=$(testlib_types)

# gen_lib unicode
testlib_unicode=$(TESTCACHE)/unicode/unicode.o
hare_testlib_deps+=$(testlib_unicode)

# gen_lib unix
testlib_unix=$(TESTCACHE)/unix/unix.o
hare_testlib_deps+=$(testlib_unix)

# gen_lib unix::hosts
testlib_unix_hosts=$(TESTCACHE)/unix/hosts/unix_hosts.o
hare_testlib_deps+=$(testlib_unix_hosts)

# gen_lib unix::passwd
testlib_unix_passwd=$(TESTCACHE)/unix/passwd/unix_passwd.o
hare_testlib_deps+=$(testlib_unix_passwd)

# gen_lib unix::poll
testlib_unix_poll=$(TESTCACHE)/unix/poll/unix_poll.o
hare_testlib_deps+=$(testlib_unix_poll)

# gen_lib unix::resolvconf
testlib_unix_resolvconf=$(TESTCACHE)/unix/resolvconf/unix_resolvconf.o
hare_testlib_deps+=$(testlib_unix_resolvconf)

# gen_lib unix::tty
testlib_unix_tty=$(TESTCACHE)/unix/tty/unix_tty.o
hare_testlib_deps+=$(testlib_unix_tty)

# gen_lib uuid
testlib_uuid=$(TESTCACHE)/uuid/uuid.o
hare_testlib_deps+=$(testlib_uuid)

# ascii
testlib_ascii_srcs= \
	$(STDLIB)/ascii/ctype.ha \
	$(STDLIB)/ascii/strcmp.ha

$(TESTCACHE)/ascii/ascii.ssa: $(testlib_ascii_srcs) $(testlib_rt) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/ascii
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nascii \
		-t$(TESTCACHE)/ascii/ascii.td $(testlib_ascii_srcs)

# bufio
testlib_bufio_srcs= \
	$(STDLIB)/bufio/buffered.ha \
	$(STDLIB)/bufio/memstream.ha \
	$(STDLIB)/bufio/scanner.ha

$(TESTCACHE)/bufio/bufio.ssa: $(testlib_bufio_srcs) $(testlib_rt) $(testlib_io) $(testlib_bytes) $(testlib_strings) $(testlib_encoding_utf8) $(testlib_errors) $(testlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/bufio
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nbufio \
		-t$(TESTCACHE)/bufio/bufio.td $(testlib_bufio_srcs)

# bytes
testlib_bytes_srcs= \
	$(STDLIB)/bytes/contains.ha \
	$(STDLIB)/bytes/copy.ha \
	$(STDLIB)/bytes/equal.ha \
	$(STDLIB)/bytes/index.ha \
	$(STDLIB)/bytes/reverse.ha \
	$(STDLIB)/bytes/tokenize.ha \
	$(STDLIB)/bytes/two_way.ha

$(TESTCACHE)/bytes/bytes.ssa: $(testlib_bytes_srcs) $(testlib_rt) $(testlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/bytes
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nbytes \
		-t$(TESTCACHE)/bytes/bytes.td $(testlib_bytes_srcs)

# compress::flate
testlib_compress_flate_srcs= \
	$(STDLIB)/compress/flate/inflate.ha

$(TESTCACHE)/compress/flate/compress_flate.ssa: $(testlib_compress_flate_srcs) $(testlib_rt) $(testlib_bufio) $(testlib_bytes) $(testlib_endian) $(testlib_errors) $(testlib_io) $(testlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/compress/flate
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ncompress::flate \
		-t$(TESTCACHE)/compress/flate/compress_flate.td $(testlib_compress_flate_srcs)

# compress::zlib
testlib_compress_zlib_srcs= \
	$(STDLIB)/compress/zlib/data+test.ha \
	$(STDLIB)/compress/zlib/reader.ha

$(TESTCACHE)/compress/zlib/compress_zlib.ssa: $(testlib_compress_zlib_srcs) $(testlib_rt) $(testlib_bufio) $(testlib_bytes) $(testlib_compress_flate) $(testlib_endian) $(testlib_errors) $(testlib_hash) $(testlib_hash_adler32) $(testlib_io) $(testlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/compress/zlib
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ncompress::zlib \
		-t$(TESTCACHE)/compress/zlib/compress_zlib.td $(testlib_compress_zlib_srcs)

# crypto::blake2b
testlib_crypto_blake2b_srcs= \
	$(STDLIB)/crypto/blake2b/blake2b.ha \
	$(STDLIB)/crypto/blake2b/+test.ha \
	$(STDLIB)/crypto/blake2b/vectors+test.ha

$(TESTCACHE)/crypto/blake2b/crypto_blake2b.ssa: $(testlib_crypto_blake2b_srcs) $(testlib_rt) $(testlib_encoding_hex) $(testlib_fmt) $(testlib_hash) $(testlib_io) $(testlib_strings) $(testlib_strio) $(testlib_crypto_math) $(testlib_endian)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/crypto/blake2b
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ncrypto::blake2b \
		-t$(TESTCACHE)/crypto/blake2b/crypto_blake2b.td $(testlib_crypto_blake2b_srcs)

# crypto::math
testlib_crypto_math_srcs= \
	$(STDLIB)/crypto/math/bits.ha

$(TESTCACHE)/crypto/math/crypto_math.ssa: $(testlib_crypto_math_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/crypto/math
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ncrypto::math \
		-t$(TESTCACHE)/crypto/math/crypto_math.td $(testlib_crypto_math_srcs)

# crypto::random
testlib_crypto_random_srcs= \
	$(STDLIB)/crypto/random/$(PLATFORM).ha \
	$(STDLIB)/crypto/random/random.ha

$(TESTCACHE)/crypto/random/crypto_random.ssa: $(testlib_crypto_random_srcs) $(testlib_rt) $(testlib_rt) $(testlib_io) $(testlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/crypto/random
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ncrypto::random \
		-t$(TESTCACHE)/crypto/random/crypto_random.td $(testlib_crypto_random_srcs)

# crypto::md5
testlib_crypto_md5_srcs= \
	$(STDLIB)/crypto/md5/md5.ha \
	$(STDLIB)/crypto/md5/+test.ha

$(TESTCACHE)/crypto/md5/crypto_md5.ssa: $(testlib_crypto_md5_srcs) $(testlib_rt) $(testlib_hash) $(testlib_io) $(testlib_endian) $(testlib_fmt) $(testlib_strio) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/crypto/md5
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ncrypto::md5 \
		-t$(TESTCACHE)/crypto/md5/crypto_md5.td $(testlib_crypto_md5_srcs)

# crypto::sha1
testlib_crypto_sha1_srcs= \
	$(STDLIB)/crypto/sha1/sha1.ha \
	$(STDLIB)/crypto/sha1/+test.ha

$(TESTCACHE)/crypto/sha1/crypto_sha1.ssa: $(testlib_crypto_sha1_srcs) $(testlib_rt) $(testlib_hash) $(testlib_io) $(testlib_endian) $(testlib_fmt) $(testlib_strio) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/crypto/sha1
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ncrypto::sha1 \
		-t$(TESTCACHE)/crypto/sha1/crypto_sha1.td $(testlib_crypto_sha1_srcs)

# crypto::sha256
testlib_crypto_sha256_srcs= \
	$(STDLIB)/crypto/sha256/sha256.ha \
	$(STDLIB)/crypto/sha256/+test.ha

$(TESTCACHE)/crypto/sha256/crypto_sha256.ssa: $(testlib_crypto_sha256_srcs) $(testlib_rt) $(testlib_hash) $(testlib_io) $(testlib_endian) $(testlib_fmt) $(testlib_strio) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/crypto/sha256
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ncrypto::sha256 \
		-t$(TESTCACHE)/crypto/sha256/crypto_sha256.td $(testlib_crypto_sha256_srcs)

# crypto::sha512
testlib_crypto_sha512_srcs= \
	$(STDLIB)/crypto/sha512/sha512.ha \
	$(STDLIB)/crypto/sha512/+test.ha

$(TESTCACHE)/crypto/sha512/crypto_sha512.ssa: $(testlib_crypto_sha512_srcs) $(testlib_rt) $(testlib_hash) $(testlib_io) $(testlib_endian) $(testlib_fmt) $(testlib_strio) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/crypto/sha512
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ncrypto::sha512 \
		-t$(TESTCACHE)/crypto/sha512/crypto_sha512.td $(testlib_crypto_sha512_srcs)

# dirs
testlib_dirs_srcs= \
	$(STDLIB)/dirs/xdg.ha

$(TESTCACHE)/dirs/dirs.ssa: $(testlib_dirs_srcs) $(testlib_rt) $(testlib_fs) $(testlib_os) $(testlib_path)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/dirs
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ndirs \
		-t$(TESTCACHE)/dirs/dirs.td $(testlib_dirs_srcs)

# encoding::base64
testlib_encoding_base64_srcs= \
	$(STDLIB)/encoding/base64/base64.ha

$(TESTCACHE)/encoding/base64/encoding_base64.ssa: $(testlib_encoding_base64_srcs) $(testlib_rt) $(testlib_bufio) $(testlib_bytes) $(testlib_io) $(testlib_strio) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/encoding/base64
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nencoding::base64 \
		-t$(TESTCACHE)/encoding/base64/encoding_base64.td $(testlib_encoding_base64_srcs)

# encoding::hex
testlib_encoding_hex_srcs= \
	$(STDLIB)/encoding/hex/hex.ha

$(TESTCACHE)/encoding/hex/encoding_hex.ssa: $(testlib_encoding_hex_srcs) $(testlib_rt) $(testlib_ascii) $(testlib_bytes) $(testlib_fmt) $(testlib_io) $(testlib_strconv) $(testlib_strio) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/encoding/hex
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nencoding::hex \
		-t$(TESTCACHE)/encoding/hex/encoding_hex.td $(testlib_encoding_hex_srcs)

# encoding::utf8
testlib_encoding_utf8_srcs= \
	$(STDLIB)/encoding/utf8/decode.ha \
	$(STDLIB)/encoding/utf8/encode.ha \
	$(STDLIB)/encoding/utf8/rune.ha

$(TESTCACHE)/encoding/utf8/encoding_utf8.ssa: $(testlib_encoding_utf8_srcs) $(testlib_rt) $(testlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/encoding/utf8
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nencoding::utf8 \
		-t$(TESTCACHE)/encoding/utf8/encoding_utf8.td $(testlib_encoding_utf8_srcs)

# endian
testlib_endian_srcs= \
	$(STDLIB)/endian/big.ha \
	$(STDLIB)/endian/network.ha \
	$(STDLIB)/endian/little.ha \
	$(STDLIB)/endian/endian.ha \
	$(STDLIB)/endian/host$(ARCH).ha

$(TESTCACHE)/endian/endian.ssa: $(testlib_endian_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/endian
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nendian \
		-t$(TESTCACHE)/endian/endian.td $(testlib_endian_srcs)

# errors
testlib_errors_srcs= \
	$(STDLIB)/errors/common.ha \
	$(STDLIB)/errors/opaque.ha \
	$(STDLIB)/errors/string.ha \
	$(STDLIB)/errors/rt.ha

$(TESTCACHE)/errors/errors.ssa: $(testlib_errors_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/errors
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nerrors \
		-t$(TESTCACHE)/errors/errors.td $(testlib_errors_srcs)

# fmt
testlib_fmt_srcs= \
	$(STDLIB)/fmt/fmt.ha

$(TESTCACHE)/fmt/fmt.ssa: $(testlib_fmt_srcs) $(testlib_rt) $(testlib_bufio) $(testlib_io) $(testlib_os) $(testlib_strconv) $(testlib_strings) $(testlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/fmt
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nfmt \
		-t$(TESTCACHE)/fmt/fmt.td $(testlib_fmt_srcs)

# format::elf
testlib_format_elf_srcs= \
	$(STDLIB)/format/elf/$(ARCH).ha \
	$(STDLIB)/format/elf/$(PLATFORM).ha \
	$(STDLIB)/format/elf/types.ha

$(TESTCACHE)/format/elf/format_elf.ssa: $(testlib_format_elf_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/format/elf
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nformat::elf \
		-t$(TESTCACHE)/format/elf/format_elf.td $(testlib_format_elf_srcs)

# format::xml
testlib_format_xml_srcs= \
	$(STDLIB)/format/xml/types.ha \
	$(STDLIB)/format/xml/parser.ha \
	$(STDLIB)/format/xml/chars.ha \
	$(STDLIB)/format/xml/+test.ha

$(TESTCACHE)/format/xml/format_xml.ssa: $(testlib_format_xml_srcs) $(testlib_rt) $(testlib_io) $(testlib_bufio) $(testlib_strings) $(testlib_ascii) $(testlib_strio) $(testlib_os)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/format/xml
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nformat::xml \
		-t$(TESTCACHE)/format/xml/format_xml.td $(testlib_format_xml_srcs)

# fs
testlib_fs_srcs= \
	$(STDLIB)/fs/types.ha \
	$(STDLIB)/fs/fs.ha \
	$(STDLIB)/fs/util.ha

$(TESTCACHE)/fs/fs.ssa: $(testlib_fs_srcs) $(testlib_rt) $(testlib_io) $(testlib_strings) $(testlib_path) $(testlib_time) $(testlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/fs
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nfs \
		-t$(TESTCACHE)/fs/fs.td $(testlib_fs_srcs)

# fs::mem
testlib_fs_mem_srcs= \
	$(STDLIB)/fs/mem/mem.ha \
	$(STDLIB)/fs/mem/stream.ha \
	$(STDLIB)/fs/mem/util.ha \
	$(STDLIB)/fs/mem/+test.ha

$(TESTCACHE)/fs/mem/fs_mem.ssa: $(testlib_fs_mem_srcs) $(testlib_rt) $(testlib_bufio) $(testlib_errors) $(testlib_fs) $(testlib_hash) $(testlib_hash_fnv) $(testlib_io) $(testlib_path) $(testlib_strconv) $(testlib_strings) $(testlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/fs/mem
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nfs::mem \
		-t$(TESTCACHE)/fs/mem/fs_mem.td $(testlib_fs_mem_srcs)

# getopt
testlib_getopt_srcs= \
	$(STDLIB)/getopt/getopts.ha

$(TESTCACHE)/getopt/getopt.ssa: $(testlib_getopt_srcs) $(testlib_rt) $(testlib_encoding_utf8) $(testlib_fmt) $(testlib_io) $(testlib_os) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/getopt
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ngetopt \
		-t$(TESTCACHE)/getopt/getopt.td $(testlib_getopt_srcs)

# hare::ast
testlib_hare_ast_srcs= \
	$(STDLIB)/hare/ast/decl.ha \
	$(STDLIB)/hare/ast/expr.ha \
	$(STDLIB)/hare/ast/ident.ha \
	$(STDLIB)/hare/ast/import.ha \
	$(STDLIB)/hare/ast/type.ha \
	$(STDLIB)/hare/ast/unit.ha

$(TESTCACHE)/hare/ast/hare_ast.ssa: $(testlib_hare_ast_srcs) $(testlib_rt) $(testlib_hare_lex) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hare/ast
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhare::ast \
		-t$(TESTCACHE)/hare/ast/hare_ast.td $(testlib_hare_ast_srcs)

# hare::lex
testlib_hare_lex_srcs= \
	$(STDLIB)/hare/lex/token.ha \
	$(STDLIB)/hare/lex/lex.ha \
	$(STDLIB)/hare/lex/+test.ha

$(TESTCACHE)/hare/lex/hare_lex.ssa: $(testlib_hare_lex_srcs) $(testlib_rt) $(testlib_io) $(testlib_bufio) $(testlib_strings) $(testlib_types) $(testlib_fmt) $(testlib_sort) $(testlib_strio)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hare/lex
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhare::lex \
		-t$(TESTCACHE)/hare/lex/hare_lex.td $(testlib_hare_lex_srcs)

# hare::module
testlib_hare_module_srcs= \
	$(STDLIB)/hare/module/types.ha \
	$(STDLIB)/hare/module/context.ha \
	$(STDLIB)/hare/module/scan.ha \
	$(STDLIB)/hare/module/manifest.ha

$(TESTCACHE)/hare/module/hare_module.ssa: $(testlib_hare_module_srcs) $(testlib_rt) $(testlib_hare_ast) $(testlib_hare_lex) $(testlib_hare_parse) $(testlib_hare_unparse) $(testlib_strio) $(testlib_fs) $(testlib_io) $(testlib_strings) $(testlib_hash) $(testlib_crypto_sha256) $(testlib_dirs) $(testlib_bytes) $(testlib_encoding_utf8) $(testlib_ascii) $(testlib_fmt) $(testlib_time) $(testlib_slice) $(testlib_bufio) $(testlib_strconv) $(testlib_os) $(testlib_encoding_hex) $(testlib_sort) $(testlib_errors) $(testlib_temp)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hare/module
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhare::module \
		-t$(TESTCACHE)/hare/module/hare_module.td $(testlib_hare_module_srcs)

# hare::parse
testlib_hare_parse_srcs= \
	$(STDLIB)/hare/parse/decl.ha \
	$(STDLIB)/hare/parse/expr.ha \
	$(STDLIB)/hare/parse/ident.ha \
	$(STDLIB)/hare/parse/import.ha \
	$(STDLIB)/hare/parse/parse.ha \
	$(STDLIB)/hare/parse/type.ha \
	$(STDLIB)/hare/parse/unit.ha \
	$(STDLIB)/hare/parse/+test/expr.ha \
	$(STDLIB)/hare/parse/+test/ident.ha \
	$(STDLIB)/hare/parse/+test/loc.ha \
	$(STDLIB)/hare/parse/+test/roundtrip.ha \
	$(STDLIB)/hare/parse/+test/types.ha \
	$(STDLIB)/hare/parse/+test/unit.ha

$(TESTCACHE)/hare/parse/hare_parse.ssa: $(testlib_hare_parse_srcs) $(testlib_rt) $(testlib_bufio) $(testlib_fmt) $(testlib_hare_ast) $(testlib_hare_lex) $(testlib_hare_unparse) $(testlib_io) $(testlib_strings) $(testlib_strio) $(testlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hare/parse
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhare::parse \
		-t$(TESTCACHE)/hare/parse/hare_parse.td $(testlib_hare_parse_srcs)

# hare::types
testlib_hare_types_srcs= \
	$(STDLIB)/hare/types/arch.ha \
	$(STDLIB)/hare/types/builtins.ha \
	$(STDLIB)/hare/types/class.ha \
	$(STDLIB)/hare/types/hash.ha \
	$(STDLIB)/hare/types/lookup.ha \
	$(STDLIB)/hare/types/store.ha \
	$(STDLIB)/hare/types/types.ha \
	$(STDLIB)/hare/types/+test.ha

$(TESTCACHE)/hare/types/hare_types.ssa: $(testlib_hare_types_srcs) $(testlib_rt) $(testlib_hare_ast) $(testlib_hare_parse) $(testlib_hash) $(testlib_hash_fnv) $(testlib_endian)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hare/types
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhare::types \
		-t$(TESTCACHE)/hare/types/hare_types.td $(testlib_hare_types_srcs)

# hare::unit
testlib_hare_unit_srcs= \
	$(STDLIB)/hare/unit/check.ha \
	$(STDLIB)/hare/unit/context.ha \
	$(STDLIB)/hare/unit/errors.ha \
	$(STDLIB)/hare/unit/expr.ha \
	$(STDLIB)/hare/unit/process.ha \
	$(STDLIB)/hare/unit/scan.ha \
	$(STDLIB)/hare/unit/scope.ha \
	$(STDLIB)/hare/unit/unit.ha \
	$(STDLIB)/hare/unit/+test.ha

$(TESTCACHE)/hare/unit/hare_unit.ssa: $(testlib_hare_unit_srcs) $(testlib_rt) $(testlib_hare_ast) $(testlib_hare_types) $(testlib_hash) $(testlib_hash_fnv) $(testlib_strings) $(testlib_hare_lex) $(testlib_bufio) $(testlib_hare_parse)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hare/unit
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhare::unit \
		-t$(TESTCACHE)/hare/unit/hare_unit.td $(testlib_hare_unit_srcs)

# hare::unparse
testlib_hare_unparse_srcs= \
	$(STDLIB)/hare/unparse/expr.ha \
	$(STDLIB)/hare/unparse/decl.ha \
	$(STDLIB)/hare/unparse/ident.ha \
	$(STDLIB)/hare/unparse/import.ha \
	$(STDLIB)/hare/unparse/type.ha \
	$(STDLIB)/hare/unparse/unit.ha \
	$(STDLIB)/hare/unparse/util.ha

$(TESTCACHE)/hare/unparse/hare_unparse.ssa: $(testlib_hare_unparse_srcs) $(testlib_rt) $(testlib_fmt) $(testlib_io) $(testlib_strio) $(testlib_hare_ast)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hare/unparse
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhare::unparse \
		-t$(TESTCACHE)/hare/unparse/hare_unparse.td $(testlib_hare_unparse_srcs)

# hash
testlib_hash_srcs= \
	$(STDLIB)/hash/hash.ha

$(TESTCACHE)/hash/hash.ssa: $(testlib_hash_srcs) $(testlib_rt) $(testlib_io) $(testlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hash
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhash \
		-t$(TESTCACHE)/hash/hash.td $(testlib_hash_srcs)

# hash::adler32
testlib_hash_adler32_srcs= \
	$(STDLIB)/hash/adler32/adler32.ha

$(TESTCACHE)/hash/adler32/hash_adler32.ssa: $(testlib_hash_adler32_srcs) $(testlib_rt) $(testlib_endian) $(testlib_hash) $(testlib_io) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hash/adler32
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhash::adler32 \
		-t$(TESTCACHE)/hash/adler32/hash_adler32.td $(testlib_hash_adler32_srcs)

# hash::crc16
testlib_hash_crc16_srcs= \
	$(STDLIB)/hash/crc16/crc16.ha

$(TESTCACHE)/hash/crc16/hash_crc16.ssa: $(testlib_hash_crc16_srcs) $(testlib_rt) $(testlib_endian) $(testlib_hash) $(testlib_io) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hash/crc16
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhash::crc16 \
		-t$(TESTCACHE)/hash/crc16/hash_crc16.td $(testlib_hash_crc16_srcs)

# hash::crc32
testlib_hash_crc32_srcs= \
	$(STDLIB)/hash/crc32/crc32.ha

$(TESTCACHE)/hash/crc32/hash_crc32.ssa: $(testlib_hash_crc32_srcs) $(testlib_rt) $(testlib_endian) $(testlib_hash) $(testlib_io) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hash/crc32
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhash::crc32 \
		-t$(TESTCACHE)/hash/crc32/hash_crc32.td $(testlib_hash_crc32_srcs)

# hash::crc64
testlib_hash_crc64_srcs= \
	$(STDLIB)/hash/crc64/crc64.ha

$(TESTCACHE)/hash/crc64/hash_crc64.ssa: $(testlib_hash_crc64_srcs) $(testlib_rt) $(testlib_endian) $(testlib_hash) $(testlib_io) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hash/crc64
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhash::crc64 \
		-t$(TESTCACHE)/hash/crc64/hash_crc64.td $(testlib_hash_crc64_srcs)

# hash::fnv
testlib_hash_fnv_srcs= \
	$(STDLIB)/hash/fnv/fnv.ha

$(TESTCACHE)/hash/fnv/hash_fnv.ssa: $(testlib_hash_fnv_srcs) $(testlib_rt) $(testlib_hash) $(testlib_io) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hash/fnv
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhash::fnv \
		-t$(TESTCACHE)/hash/fnv/hash_fnv.td $(testlib_hash_fnv_srcs)

# io
testlib_io_srcs= \
	$(STDLIB)/io/arch$(ARCH).ha \
	$(STDLIB)/io/copy.ha \
	$(STDLIB)/io/drain.ha \
	$(STDLIB)/io/limit.ha \
	$(STDLIB)/io/println$(PLATFORM).ha \
	$(STDLIB)/io/stream.ha \
	$(STDLIB)/io/tee.ha \
	$(STDLIB)/io/types.ha \
	$(STDLIB)/io/$(PLATFORM)/file.ha \
	$(STDLIB)/io/+test/copy.ha \
	$(STDLIB)/io/+test/limit.ha \
	$(STDLIB)/io/+test/stream.ha

$(TESTCACHE)/io/io.ssa: $(testlib_io_srcs) $(testlib_rt) $(testlib_strings) $(testlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/io
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nio \
		-t$(TESTCACHE)/io/io.td $(testlib_io_srcs)

# linux
testlib_linux_srcs= \
	$(STDLIB)/linux/start.ha \
	$(STDLIB)/linux/env.ha

$(TESTCACHE)/linux/linux.ssa: $(testlib_linux_srcs) $(testlib_rt) $(testlib_format_elf)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/linux
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nlinux \
		-t$(TESTCACHE)/linux/linux.td $(testlib_linux_srcs)

# linux::signalfd
testlib_linux_signalfd_srcs= \
	$(STDLIB)/linux/signalfd/signalfd.ha

$(TESTCACHE)/linux/signalfd/linux_signalfd.ssa: $(testlib_linux_signalfd_srcs) $(testlib_rt) $(testlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/linux/signalfd
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nlinux::signalfd \
		-t$(TESTCACHE)/linux/signalfd/linux_signalfd.td $(testlib_linux_signalfd_srcs)

# linux::io_uring
testlib_linux_io_uring_srcs= \
	$(STDLIB)/linux/io_uring/cqe.ha \
	$(STDLIB)/linux/io_uring/queue.ha \
	$(STDLIB)/linux/io_uring/register.ha \
	$(STDLIB)/linux/io_uring/setup.ha \
	$(STDLIB)/linux/io_uring/sqe.ha \
	$(STDLIB)/linux/io_uring/uring.ha

$(TESTCACHE)/linux/io_uring/linux_io_uring.ssa: $(testlib_linux_io_uring_srcs) $(testlib_rt) $(testlib_errors) $(testlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/linux/io_uring
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nlinux::io_uring \
		-t$(TESTCACHE)/linux/io_uring/linux_io_uring.td $(testlib_linux_io_uring_srcs)

# linux::vdso
testlib_linux_vdso_srcs= \
	$(STDLIB)/linux/vdso/vdso.ha

$(TESTCACHE)/linux/vdso/linux_vdso.ssa: $(testlib_linux_vdso_srcs) $(testlib_rt) $(testlib_linux) $(testlib_strings) $(testlib_format_elf)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/linux/vdso
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nlinux::vdso \
		-t$(TESTCACHE)/linux/vdso/linux_vdso.td $(testlib_linux_vdso_srcs)

# math
# math
testlib_math_srcs= \
	$(STDLIB)/math/testdata.ha \
	$(STDLIB)/math/math.ha \
	$(STDLIB)/math/floats.ha \
	$(STDLIB)/math/ints.ha \
	$(STDLIB)/math/uints.ha \
	$(STDLIB)/math/trig.ha

$(TESTCACHE)/math/math.ssa: $(testlib_math_srcs) $(testlib_rt) $(testlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/math
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nmath \
		-t$(TESTCACHE)/math/math.td $(testlib_math_srcs)

# net
# net
testlib_net_srcs= \
	$(STDLIB)/net/$(PLATFORM).ha \
	$(STDLIB)/net/errors.ha \
	$(STDLIB)/net/listener.ha

$(TESTCACHE)/net/net.ssa: $(testlib_net_srcs) $(testlib_rt) $(testlib_io) $(testlib_os) $(testlib_strings) $(testlib_net_ip) $(testlib_errors) $(testlib_rt) $(testlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/net
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nnet \
		-t$(TESTCACHE)/net/net.td $(testlib_net_srcs)

# net::dial
# net::dial
testlib_net_dial_srcs= \
	$(STDLIB)/net/dial/registry.ha \
	$(STDLIB)/net/dial/dial.ha \
	$(STDLIB)/net/dial/ip.ha \
	$(STDLIB)/net/dial/resolve.ha

$(TESTCACHE)/net/dial/net_dial.ssa: $(testlib_net_dial_srcs) $(testlib_rt) $(testlib_io) $(testlib_net) $(testlib_net_ip) $(testlib_net_tcp) $(testlib_net_udp) $(testlib_net_dns) $(testlib_crypto_random) $(testlib_strconv) $(testlib_strings) $(testlib_unix_hosts)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/net/dial
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nnet::dial \
		-t$(TESTCACHE)/net/dial/net_dial.td $(testlib_net_dial_srcs)

# net::dns
# net::dns
testlib_net_dns_srcs= \
	$(STDLIB)/net/dns/decode.ha \
	$(STDLIB)/net/dns/error.ha \
	$(STDLIB)/net/dns/encode.ha \
	$(STDLIB)/net/dns/query.ha \
	$(STDLIB)/net/dns/types.ha

$(TESTCACHE)/net/dns/net_dns.ssa: $(testlib_net_dns_srcs) $(testlib_rt) $(testlib_ascii) $(testlib_endian) $(testlib_net) $(testlib_net_udp) $(testlib_net_ip) $(testlib_fmt) $(testlib_strings) $(testlib_unix_resolvconf) $(testlib_unix_poll) $(testlib_rt) $(testlib_time) $(testlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/net/dns
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nnet::dns \
		-t$(TESTCACHE)/net/dns/net_dns.td $(testlib_net_dns_srcs)

# net::ip
testlib_net_ip_srcs= \
	$(STDLIB)/net/ip/ip.ha \
	$(STDLIB)/net/ip/$(PLATFORM).ha \
	$(STDLIB)/net/ip/+test.ha

$(TESTCACHE)/net/ip/net_ip.ssa: $(testlib_net_ip_srcs) $(testlib_rt) $(testlib_bytes) $(testlib_io) $(testlib_strconv) $(testlib_strings) $(testlib_strio) $(testlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/net/ip
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nnet::ip \
		-t$(TESTCACHE)/net/ip/net_ip.td $(testlib_net_ip_srcs)

# net::tcp
# net::tcp
testlib_net_tcp_srcs= \
	$(STDLIB)/net/tcp/$(PLATFORM).ha \
	$(STDLIB)/net/tcp/listener.ha \
	$(STDLIB)/net/tcp/options.ha

$(TESTCACHE)/net/tcp/net_tcp.ssa: $(testlib_net_tcp_srcs) $(testlib_rt) $(testlib_io) $(testlib_net) $(testlib_net_ip) $(testlib_os) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/net/tcp
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nnet::tcp \
		-t$(TESTCACHE)/net/tcp/net_tcp.td $(testlib_net_tcp_srcs)

# net::udp
# net::udp
testlib_net_udp_srcs= \
	$(STDLIB)/net/udp/$(PLATFORM).ha \
	$(STDLIB)/net/udp/options.ha

$(TESTCACHE)/net/udp/net_udp.ssa: $(testlib_net_udp_srcs) $(testlib_rt) $(testlib_net) $(testlib_net_ip) $(testlib_errors) $(testlib_rt) $(testlib_os) $(testlib_io)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/net/udp
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nnet::udp \
		-t$(TESTCACHE)/net/udp/net_udp.td $(testlib_net_udp_srcs)

# net::unix
# net::unix
testlib_net_unix_srcs= \
	$(STDLIB)/net/unix/$(PLATFORM).ha \
	$(STDLIB)/net/unix/addr.ha \
	$(STDLIB)/net/unix/dial.ha \
	$(STDLIB)/net/unix/listener.ha \
	$(STDLIB)/net/unix/options.ha

$(TESTCACHE)/net/unix/net_unix.ssa: $(testlib_net_unix_srcs) $(testlib_rt) $(testlib_net) $(testlib_errors) $(testlib_os) $(testlib_io) $(testlib_strings) $(testlib_types) $(testlib_fmt) $(testlib_net_dial)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/net/unix
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nnet::unix \
		-t$(TESTCACHE)/net/unix/net_unix.td $(testlib_net_unix_srcs)

# math::random
testlib_math_random_srcs= \
	$(STDLIB)/math/random/random.ha

$(TESTCACHE)/math/random/math_random.ssa: $(testlib_math_random_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/math/random
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nmath::random \
		-t$(TESTCACHE)/math/random/math_random.td $(testlib_math_random_srcs)

# os
testlib_os_srcs= \
	$(STDLIB)/os/$(PLATFORM)/environ.ha \
	$(STDLIB)/os/$(PLATFORM)/exit.ha \
	$(STDLIB)/os/$(PLATFORM)/dirfdfs.ha \
	$(STDLIB)/os/$(PLATFORM)/stdfd.ha \
	$(STDLIB)/os/$(PLATFORM)/fs.ha \
	$(STDLIB)/os/stdfd.ha \
	$(STDLIB)/os/fs.ha

$(TESTCACHE)/os/os.ssa: $(testlib_os_srcs) $(testlib_rt) $(testlib_io) $(testlib_strings) $(testlib_types) $(testlib_fs) $(testlib_encoding_utf8) $(testlib_bytes) $(testlib_bufio) $(testlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/os
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nos \
		-t$(TESTCACHE)/os/os.td $(testlib_os_srcs)

# os::exec
testlib_os_exec_srcs= \
	$(STDLIB)/os/exec/exec$(PLATFORM).ha \
	$(STDLIB)/os/exec/process$(PLATFORM).ha \
	$(STDLIB)/os/exec/types.ha \
	$(STDLIB)/os/exec/cmd.ha

$(TESTCACHE)/os/exec/os_exec.ssa: $(testlib_os_exec_srcs) $(testlib_rt) $(testlib_os) $(testlib_strings) $(testlib_fmt) $(testlib_bytes) $(testlib_path) $(testlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/os/exec
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nos::exec \
		-t$(TESTCACHE)/os/exec/os_exec.td $(testlib_os_exec_srcs)

# path
testlib_path_srcs= \
	$(STDLIB)/path/$(PLATFORM).ha \
	$(STDLIB)/path/util.ha \
	$(STDLIB)/path/join.ha \
	$(STDLIB)/path/names.ha \
	$(STDLIB)/path/iter.ha

$(TESTCACHE)/path/path.ssa: $(testlib_path_srcs) $(testlib_rt) $(testlib_strings) $(testlib_bufio) $(testlib_bytes)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/path
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Npath \
		-t$(TESTCACHE)/path/path.td $(testlib_path_srcs)

# slice
testlib_slice_srcs= \
	$(STDLIB)/slice/reverse.ha \
	$(STDLIB)/slice/void.ha

$(TESTCACHE)/slice/slice.ssa: $(testlib_slice_srcs) $(testlib_rt) $(testlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/slice
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nslice \
		-t$(TESTCACHE)/slice/slice.td $(testlib_slice_srcs)

# sort
testlib_sort_srcs= \
	$(STDLIB)/sort/search.ha \
	$(STDLIB)/sort/sort.ha \
	$(STDLIB)/sort/+test.ha

$(TESTCACHE)/sort/sort.ssa: $(testlib_sort_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/sort
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nsort \
		-t$(TESTCACHE)/sort/sort.td $(testlib_sort_srcs)

# strconv
testlib_strconv_srcs= \
	$(STDLIB)/strconv/types.ha \
	$(STDLIB)/strconv/itos.ha \
	$(STDLIB)/strconv/utos.ha \
	$(STDLIB)/strconv/stou.ha \
	$(STDLIB)/strconv/stoi.ha \
	$(STDLIB)/strconv/numeric.ha \
	$(STDLIB)/strconv/ftos.ha \
	$(STDLIB)/strconv/stof.ha \
	$(STDLIB)/strconv/stof_data.ha \
	$(STDLIB)/strconv/+test/stou.ha \
	$(STDLIB)/strconv/+test/stoi.ha

$(TESTCACHE)/strconv/strconv.ssa: $(testlib_strconv_srcs) $(testlib_rt) $(testlib_types) $(testlib_strings) $(testlib_ascii) $(testlib_math)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/strconv
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nstrconv \
		-t$(TESTCACHE)/strconv/strconv.td $(testlib_strconv_srcs)

# strings
testlib_strings_srcs= \
	$(STDLIB)/strings/concat.ha \
	$(STDLIB)/strings/contains.ha \
	$(STDLIB)/strings/cstrings.ha \
	$(STDLIB)/strings/dup.ha \
	$(STDLIB)/strings/iter.ha \
	$(STDLIB)/strings/sub.ha \
	$(STDLIB)/strings/suffix.ha \
	$(STDLIB)/strings/tokenize.ha \
	$(STDLIB)/strings/utf8.ha \
	$(STDLIB)/strings/index.ha \
	$(STDLIB)/strings/trim.ha

$(TESTCACHE)/strings/strings.ssa: $(testlib_strings_srcs) $(testlib_rt) $(testlib_bytes) $(testlib_encoding_utf8) $(testlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/strings
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nstrings \
		-t$(TESTCACHE)/strings/strings.td $(testlib_strings_srcs)

# strio
testlib_strio_srcs= \
	$(STDLIB)/strio/dynamic.ha \
	$(STDLIB)/strio/fixed.ha \
	$(STDLIB)/strio/ops.ha

$(TESTCACHE)/strio/strio.ssa: $(testlib_strio_srcs) $(testlib_rt) $(testlib_io) $(testlib_strings) $(testlib_encoding_utf8) $(testlib_errors)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/strio
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nstrio \
		-t$(TESTCACHE)/strio/strio.td $(testlib_strio_srcs)

# temp
testlib_temp_srcs= \
	$(STDLIB)/temp/$(PLATFORM).ha

$(TESTCACHE)/temp/temp.ssa: $(testlib_temp_srcs) $(testlib_rt) $(testlib_crypto_random) $(testlib_encoding_hex) $(testlib_fs) $(testlib_io) $(testlib_os) $(testlib_path) $(testlib_strio) $(testlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/temp
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ntemp \
		-t$(TESTCACHE)/temp/temp.td $(testlib_temp_srcs)

# time
testlib_time_srcs= \
	$(STDLIB)/time/$(PLATFORM)/functions.ha \
	$(STDLIB)/time/$(PLATFORM)/$(ARCH).ha \
	$(STDLIB)/time/arithm.ha \
	$(STDLIB)/time/types.ha

$(TESTCACHE)/time/time.ssa: $(testlib_time_srcs) $(testlib_rt) $(testlib_linux_vdso)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/time
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ntime \
		-t$(TESTCACHE)/time/time.td $(testlib_time_srcs)

# types
testlib_types_srcs= \
	$(STDLIB)/types/limits.ha \
	$(STDLIB)/types/classes.ha \
	$(STDLIB)/types/arch$(ARCH).ha

$(TESTCACHE)/types/types.ssa: $(testlib_types_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/types
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ntypes \
		-t$(TESTCACHE)/types/types.td $(testlib_types_srcs)

# unicode
testlib_unicode_srcs= \
	$(STDLIB)/unicode/properties.ha

$(TESTCACHE)/unicode/unicode.ssa: $(testlib_unicode_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/unicode
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nunicode \
		-t$(TESTCACHE)/unicode/unicode.td $(testlib_unicode_srcs)

# unix
testlib_unix_srcs= \
	$(STDLIB)/unix/$(PLATFORM)/nice.ha \
	$(STDLIB)/unix/$(PLATFORM)/umask.ha \
	$(STDLIB)/unix/getuid.ha \
	$(STDLIB)/unix/setuid.ha

$(TESTCACHE)/unix/unix.ssa: $(testlib_unix_srcs) $(testlib_rt) $(testlib_errors) $(testlib_fs)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/unix
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nunix \
		-t$(TESTCACHE)/unix/unix.td $(testlib_unix_srcs)

# unix::hosts
testlib_unix_hosts_srcs= \
	$(STDLIB)/unix/hosts/lookup.ha

$(TESTCACHE)/unix/hosts/unix_hosts.ssa: $(testlib_unix_hosts_srcs) $(testlib_rt) $(testlib_os) $(testlib_io) $(testlib_bufio) $(testlib_net_ip) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/unix/hosts
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nunix::hosts \
		-t$(TESTCACHE)/unix/hosts/unix_hosts.td $(testlib_unix_hosts_srcs)

# unix::passwd
testlib_unix_passwd_srcs= \
	$(STDLIB)/unix/passwd/group.ha \
	$(STDLIB)/unix/passwd/passwd.ha \
	$(STDLIB)/unix/passwd/types.ha

$(TESTCACHE)/unix/passwd/unix_passwd.ssa: $(testlib_unix_passwd_srcs) $(testlib_rt) $(testlib_bufio) $(testlib_io) $(testlib_os) $(testlib_strconv) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/unix/passwd
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nunix::passwd \
		-t$(TESTCACHE)/unix/passwd/unix_passwd.td $(testlib_unix_passwd_srcs)

# unix::poll
testlib_unix_poll_srcs= \
	$(STDLIB)/unix/poll/$(PLATFORM).ha

$(TESTCACHE)/unix/poll/unix_poll.ssa: $(testlib_unix_poll_srcs) $(testlib_rt) $(testlib_rt) $(testlib_errors) $(testlib_time)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/unix/poll
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nunix::poll \
		-t$(TESTCACHE)/unix/poll/unix_poll.td $(testlib_unix_poll_srcs)

# unix::resolvconf
testlib_unix_resolvconf_srcs= \
	$(STDLIB)/unix/resolvconf/load.ha

$(TESTCACHE)/unix/resolvconf/unix_resolvconf.ssa: $(testlib_unix_resolvconf_srcs) $(testlib_rt) $(testlib_os) $(testlib_io) $(testlib_bufio) $(testlib_net_ip) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/unix/resolvconf
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nunix::resolvconf \
		-t$(TESTCACHE)/unix/resolvconf/unix_resolvconf.td $(testlib_unix_resolvconf_srcs)

# unix::tty
testlib_unix_tty_srcs= \
	$(STDLIB)/unix/tty/types.ha \
	$(STDLIB)/unix/tty/$(PLATFORM)/isatty.ha \
	$(STDLIB)/unix/tty/$(PLATFORM)/open.ha \
	$(STDLIB)/unix/tty/$(PLATFORM)/winsize.ha

$(TESTCACHE)/unix/tty/unix_tty.ssa: $(testlib_unix_tty_srcs) $(testlib_rt) $(testlib_rt) $(testlib_fs) $(testlib_io) $(testlib_os)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/unix/tty
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nunix::tty \
		-t$(TESTCACHE)/unix/tty/unix_tty.td $(testlib_unix_tty_srcs)

# uuid
testlib_uuid_srcs= \
	$(STDLIB)/uuid/uuid.ha

$(TESTCACHE)/uuid/uuid.ssa: $(testlib_uuid_srcs) $(testlib_rt) $(testlib_crypto_random) $(testlib_strio) $(testlib_fmt) $(testlib_endian) $(testlib_io) $(testlib_bytes) $(testlib_bufio) $(testlib_strings) $(testlib_strconv)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/uuid
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nuuid \
		-t$(TESTCACHE)/uuid/uuid.td $(testlib_uuid_srcs)

