# This file is generated by the gen-stdlib script, do not edit it by hand

rtscript=$(STDLIB)/rt/hare.sc
# rt
stdlib_rt_srcs= \
	$(STDLIB)/rt/$(PLATFORM)/abort.ha \
	$(STDLIB)/rt/$(PLATFORM)/env.ha \
	$(STDLIB)/rt/$(PLATFORM)/errno.ha \
	$(STDLIB)/rt/$(PLATFORM)/types.ha \
	$(STDLIB)/rt/$(PLATFORM)/segmalloc.ha \
	$(STDLIB)/rt/$(PLATFORM)/start.ha \
	$(STDLIB)/rt/$(PLATFORM)/$(ARCH).ha \
	$(STDLIB)/rt/$(PLATFORM)/syscallno$(ARCH).ha \
	$(STDLIB)/rt/$(PLATFORM)/syscalls.ha \
	$(STDLIB)/rt/$(PLATFORM)/signal.ha \
	$(STDLIB)/rt/$(PLATFORM)/stat.ha \
	$(STDLIB)/rt/$(PLATFORM)/socket.ha \
	$(STDLIB)/rt/$(ARCH)/jmp.ha \
	$(STDLIB)/rt/ensure.ha \
	$(STDLIB)/rt/jmp.ha \
	$(STDLIB)/rt/malloc.ha \
	$(STDLIB)/rt/memcpy.ha \
	$(STDLIB)/rt/memset.ha \
	$(STDLIB)/rt/strcmp.ha \
	$(STDLIB)/rt/abort.ha \
	$(STDLIB)/rt/start.ha

$(HARECACHE)/rt/rt.ssa: $(stdlib_rt_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/rt
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nrt \
		-t$(HARECACHE)/rt/rt.td $(stdlib_rt_srcs)

$(HARECACHE)/rt/start.o: $(STDLIB)/rt/$(PLATFORM)/start$(ARCH).s
	@printf 'AS \t$@\n'
	@mkdir -p $(HARECACHE)/rt
	@$(AS) -o $@ $<

stdlib_asm=$(HARECACHE)/rt/syscall.o \
	$(HARECACHE)/rt/setjmp.o \
	$(HARECACHE)/rt/longjmp.o \
	$(HARECACHE)/rt/restore.o \
	$(HARECACHE)/rt/start.o

$(HARECACHE)/rt/syscall.o: $(STDLIB)/rt/$(PLATFORM)/syscall$(ARCH).s
	@printf 'AS \t$@\n'
	@mkdir -p $(HARECACHE)/rt
	@$(AS) -o $@ $<

$(HARECACHE)/rt/setjmp.o: $(STDLIB)/rt/$(ARCH)/setjmp.s
	@printf 'AS \t$@\n'
	@mkdir -p $(HARECACHE)/rt
	@$(AS) -o $@ $<

$(HARECACHE)/rt/longjmp.o: $(STDLIB)/rt/$(ARCH)/longjmp.s
	@printf 'AS \t$@\n'
	@mkdir -p $(HARECACHE)/rt
	@$(AS) -o $@ $<

$(HARECACHE)/rt/restore.o: $(STDLIB)/rt/$(ARCH)/restore.s
	@printf 'AS \t$@\n'
	@mkdir -p $(HARECACHE)/rt
	@$(AS) -o $@ $<

$(HARECACHE)/rt/rt.a: $(HARECACHE)/rt/rt.o $(stdlib_asm)
	@printf 'AR\t$@\n'
	@$(AR) -csr $@ $(HARECACHE)/rt/rt.o $(stdlib_asm)

stdlib_rt=$(HARECACHE)/rt/rt.a
hare_stdlib_deps+=$(stdlib_rt)

stdlib_ascii=$(HARECACHE)/ascii/ascii.o
hare_stdlib_deps+=$(stdlib_ascii)

stdlib_bufio=$(HARECACHE)/bufio/bufio.o
hare_stdlib_deps+=$(stdlib_bufio)

stdlib_bytes=$(HARECACHE)/bytes/bytes.o
hare_stdlib_deps+=$(stdlib_bytes)

stdlib_crypto_math=$(HARECACHE)/crypto/math/crypto_math.o
hare_stdlib_deps+=$(stdlib_crypto_math)

stdlib_crypto_random=$(HARECACHE)/crypto/random/crypto_random.o
hare_stdlib_deps+=$(stdlib_crypto_random)

stdlib_crypto_sha1=$(HARECACHE)/crypto/sha1/crypto_sha1.o
hare_stdlib_deps+=$(stdlib_crypto_sha1)

stdlib_crypto_sha256=$(HARECACHE)/crypto/sha256/crypto_sha256.o
hare_stdlib_deps+=$(stdlib_crypto_sha256)

stdlib_crypto_sha512=$(HARECACHE)/crypto/sha512/crypto_sha512.o
hare_stdlib_deps+=$(stdlib_crypto_sha512)

stdlib_dirs=$(HARECACHE)/dirs/dirs.o
hare_stdlib_deps+=$(stdlib_dirs)

stdlib_encoding_hex=$(HARECACHE)/encoding/hex/encoding_hex.o
hare_stdlib_deps+=$(stdlib_encoding_hex)

stdlib_encoding_utf8=$(HARECACHE)/encoding/utf8/encoding_utf8.o
hare_stdlib_deps+=$(stdlib_encoding_utf8)

stdlib_endian=$(HARECACHE)/endian/endian.o
hare_stdlib_deps+=$(stdlib_endian)

stdlib_fmt=$(HARECACHE)/fmt/fmt.o
hare_stdlib_deps+=$(stdlib_fmt)

stdlib_format_elf=$(HARECACHE)/format/elf/format_elf.o
hare_stdlib_deps+=$(stdlib_format_elf)

stdlib_fs=$(HARECACHE)/fs/fs.o
hare_stdlib_deps+=$(stdlib_fs)

stdlib_getopt=$(HARECACHE)/getopt/getopt.o
hare_stdlib_deps+=$(stdlib_getopt)

stdlib_hare_ast=$(HARECACHE)/hare/ast/hare_ast.o
hare_stdlib_deps+=$(stdlib_hare_ast)

stdlib_hare_lex=$(HARECACHE)/hare/lex/hare_lex.o
hare_stdlib_deps+=$(stdlib_hare_lex)

stdlib_hare_module=$(HARECACHE)/hare/module/hare_module.o
hare_stdlib_deps+=$(stdlib_hare_module)

stdlib_hare_parse=$(HARECACHE)/hare/parse/hare_parse.o
hare_stdlib_deps+=$(stdlib_hare_parse)

stdlib_hare_unparse=$(HARECACHE)/hare/unparse/hare_unparse.o
hare_stdlib_deps+=$(stdlib_hare_unparse)

stdlib_hash=$(HARECACHE)/hash/hash.o
hare_stdlib_deps+=$(stdlib_hash)

stdlib_hash_adler32=$(HARECACHE)/hash/adler32/hash_adler32.o
hare_stdlib_deps+=$(stdlib_hash_adler32)

stdlib_hash_fnv=$(HARECACHE)/hash/fnv/hash_fnv.o
hare_stdlib_deps+=$(stdlib_hash_fnv)

stdlib_io=$(HARECACHE)/io/io.o
hare_stdlib_deps+=$(stdlib_io)

stdlib_linux=$(HARECACHE)/linux/linux.o
hare_stdlib_deps+=$(stdlib_linux)

stdlib_linux_vdso=$(HARECACHE)/linux/vdso/linux_vdso.o
hare_stdlib_deps+=$(stdlib_linux_vdso)

stdlib_net=$(HARECACHE)/net/net.o
hare_stdlib_deps+=$(stdlib_net)

stdlib_net_ip=$(HARECACHE)/net/ip/net_ip.o
hare_stdlib_deps+=$(stdlib_net_ip)

stdlib_math_random=$(HARECACHE)/math/random/math_random.o
hare_stdlib_deps+=$(stdlib_math_random)

stdlib_os=$(HARECACHE)/os/os.o
hare_stdlib_deps+=$(stdlib_os)

stdlib_os_exec=$(HARECACHE)/os/exec/os_exec.o
hare_stdlib_deps+=$(stdlib_os_exec)

stdlib_path=$(HARECACHE)/path/path.o
hare_stdlib_deps+=$(stdlib_path)

stdlib_slice=$(HARECACHE)/slice/slice.o
hare_stdlib_deps+=$(stdlib_slice)

stdlib_sort=$(HARECACHE)/sort/sort.o
hare_stdlib_deps+=$(stdlib_sort)

stdlib_strconv=$(HARECACHE)/strconv/strconv.o
hare_stdlib_deps+=$(stdlib_strconv)

stdlib_strings=$(HARECACHE)/strings/strings.o
hare_stdlib_deps+=$(stdlib_strings)

stdlib_strio=$(HARECACHE)/strio/strio.o
hare_stdlib_deps+=$(stdlib_strio)

stdlib_temp=$(HARECACHE)/temp/temp.o
hare_stdlib_deps+=$(stdlib_temp)

stdlib_time=$(HARECACHE)/time/time.o
hare_stdlib_deps+=$(stdlib_time)

stdlib_types=$(HARECACHE)/types/types.o
hare_stdlib_deps+=$(stdlib_types)

stdlib_unicode=$(HARECACHE)/unicode/unicode.o
hare_stdlib_deps+=$(stdlib_unicode)

stdlib_unix_passwd=$(HARECACHE)/unix/passwd/unix_passwd.o
hare_stdlib_deps+=$(stdlib_unix_passwd)

stdlib_uuid=$(HARECACHE)/uuid/uuid.o
hare_stdlib_deps+=$(stdlib_uuid)

# ascii
stdlib_ascii_srcs= \
	$(STDLIB)/ascii/ctype.ha \
	$(STDLIB)/ascii/strcmp.ha

$(HARECACHE)/ascii/ascii.ssa: $(stdlib_ascii_srcs) $(stdlib_rt) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/ascii
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nascii \
		-t$(HARECACHE)/ascii/ascii.td $(stdlib_ascii_srcs)

# bufio
stdlib_bufio_srcs= \
	$(STDLIB)/bufio/buffered.ha \
	$(STDLIB)/bufio/dynamic.ha \
	$(STDLIB)/bufio/fixed.ha \
	$(STDLIB)/bufio/scanner.ha

$(HARECACHE)/bufio/bufio.ssa: $(stdlib_bufio_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_bytes) $(stdlib_strings) $(stdlib_encoding_utf8)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/bufio
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nbufio \
		-t$(HARECACHE)/bufio/bufio.td $(stdlib_bufio_srcs)

# bytes
stdlib_bytes_srcs= \
	$(STDLIB)/bytes/contains.ha \
	$(STDLIB)/bytes/copy.ha \
	$(STDLIB)/bytes/equal.ha \
	$(STDLIB)/bytes/index.ha \
	$(STDLIB)/bytes/reverse.ha \
	$(STDLIB)/bytes/tokenize.ha

$(HARECACHE)/bytes/bytes.ssa: $(stdlib_bytes_srcs) $(stdlib_rt) $(stdlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/bytes
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nbytes \
		-t$(HARECACHE)/bytes/bytes.td $(stdlib_bytes_srcs)

# crypto::math
stdlib_crypto_math_srcs= \
	$(STDLIB)/crypto/math/bits.ha

$(HARECACHE)/crypto/math/crypto_math.ssa: $(stdlib_crypto_math_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/crypto/math
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ncrypto::math \
		-t$(HARECACHE)/crypto/math/crypto_math.td $(stdlib_crypto_math_srcs)

# crypto::random
stdlib_crypto_random_srcs= \
	$(STDLIB)/crypto/random/$(PLATFORM).ha \
	$(STDLIB)/crypto/random/random.ha

$(HARECACHE)/crypto/random/crypto_random.ssa: $(stdlib_crypto_random_srcs) $(stdlib_rt) $(stdlib_rt) $(stdlib_io)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/crypto/random
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ncrypto::random \
		-t$(HARECACHE)/crypto/random/crypto_random.td $(stdlib_crypto_random_srcs)

# crypto::sha1
stdlib_crypto_sha1_srcs= \
	$(STDLIB)/crypto/sha1/sha1.ha

$(HARECACHE)/crypto/sha1/crypto_sha1.ssa: $(stdlib_crypto_sha1_srcs) $(stdlib_rt) $(stdlib_hash) $(stdlib_io) $(stdlib_endian)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/crypto/sha1
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ncrypto::sha1 \
		-t$(HARECACHE)/crypto/sha1/crypto_sha1.td $(stdlib_crypto_sha1_srcs)

# crypto::sha256
stdlib_crypto_sha256_srcs= \
	$(STDLIB)/crypto/sha256/sha256.ha

$(HARECACHE)/crypto/sha256/crypto_sha256.ssa: $(stdlib_crypto_sha256_srcs) $(stdlib_rt) $(stdlib_hash) $(stdlib_io) $(stdlib_endian)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/crypto/sha256
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ncrypto::sha256 \
		-t$(HARECACHE)/crypto/sha256/crypto_sha256.td $(stdlib_crypto_sha256_srcs)

# crypto::sha512
stdlib_crypto_sha512_srcs= \
	$(STDLIB)/crypto/sha512/sha512.ha

$(HARECACHE)/crypto/sha512/crypto_sha512.ssa: $(stdlib_crypto_sha512_srcs) $(stdlib_rt) $(stdlib_hash) $(stdlib_io) $(stdlib_endian)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/crypto/sha512
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ncrypto::sha512 \
		-t$(HARECACHE)/crypto/sha512/crypto_sha512.td $(stdlib_crypto_sha512_srcs)

# dirs
stdlib_dirs_srcs= \
	$(STDLIB)/dirs/xdg.ha

$(HARECACHE)/dirs/dirs.ssa: $(stdlib_dirs_srcs) $(stdlib_rt) $(stdlib_fs) $(stdlib_os) $(stdlib_path)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/dirs
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ndirs \
		-t$(HARECACHE)/dirs/dirs.td $(stdlib_dirs_srcs)

# encoding::hex
stdlib_encoding_hex_srcs= \
	$(STDLIB)/encoding/hex/hex.ha

$(HARECACHE)/encoding/hex/encoding_hex.ssa: $(stdlib_encoding_hex_srcs) $(stdlib_rt) $(stdlib_ascii) $(stdlib_bytes) $(stdlib_fmt) $(stdlib_io) $(stdlib_strconv) $(stdlib_strio) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/encoding/hex
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nencoding::hex \
		-t$(HARECACHE)/encoding/hex/encoding_hex.td $(stdlib_encoding_hex_srcs)

# encoding::utf8
stdlib_encoding_utf8_srcs= \
	$(STDLIB)/encoding/utf8/decode.ha \
	$(STDLIB)/encoding/utf8/encode.ha \
	$(STDLIB)/encoding/utf8/rune.ha

$(HARECACHE)/encoding/utf8/encoding_utf8.ssa: $(stdlib_encoding_utf8_srcs) $(stdlib_rt) $(stdlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/encoding/utf8
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nencoding::utf8 \
		-t$(HARECACHE)/encoding/utf8/encoding_utf8.td $(stdlib_encoding_utf8_srcs)

# endian
stdlib_endian_srcs= \
	$(STDLIB)/endian/big.ha \
	$(STDLIB)/endian/network.ha \
	$(STDLIB)/endian/little.ha \
	$(STDLIB)/endian/endian.ha \
	$(STDLIB)/endian/host$(ARCH).ha

$(HARECACHE)/endian/endian.ssa: $(stdlib_endian_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/endian
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nendian \
		-t$(HARECACHE)/endian/endian.td $(stdlib_endian_srcs)

# fmt
stdlib_fmt_srcs= \
	$(STDLIB)/fmt/fmt.ha

$(HARECACHE)/fmt/fmt.ssa: $(stdlib_fmt_srcs) $(stdlib_rt) $(stdlib_bufio) $(stdlib_io) $(stdlib_os) $(stdlib_strconv) $(stdlib_strings) $(stdlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/fmt
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nfmt \
		-t$(HARECACHE)/fmt/fmt.td $(stdlib_fmt_srcs)

# format::elf
stdlib_format_elf_srcs= \
	$(STDLIB)/format/elf/types.ha

$(HARECACHE)/format/elf/format_elf.ssa: $(stdlib_format_elf_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/format/elf
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nformat::elf \
		-t$(HARECACHE)/format/elf/format_elf.td $(stdlib_format_elf_srcs)

# fs
stdlib_fs_srcs= \
	$(STDLIB)/fs/types.ha \
	$(STDLIB)/fs/fs.ha \
	$(STDLIB)/fs/util.ha

$(HARECACHE)/fs/fs.ssa: $(stdlib_fs_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_strings) $(stdlib_path) $(stdlib_time)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/fs
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nfs \
		-t$(HARECACHE)/fs/fs.td $(stdlib_fs_srcs)

# getopt
stdlib_getopt_srcs= \
	$(STDLIB)/getopt/getopts.ha

$(HARECACHE)/getopt/getopt.ssa: $(stdlib_getopt_srcs) $(stdlib_rt) $(stdlib_encoding_utf8) $(stdlib_fmt) $(stdlib_io) $(stdlib_os) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/getopt
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ngetopt \
		-t$(HARECACHE)/getopt/getopt.td $(stdlib_getopt_srcs)

# hare::ast
stdlib_hare_ast_srcs= \
	$(STDLIB)/hare/ast/decl.ha \
	$(STDLIB)/hare/ast/expr.ha \
	$(STDLIB)/hare/ast/ident.ha \
	$(STDLIB)/hare/ast/import.ha \
	$(STDLIB)/hare/ast/type.ha \
	$(STDLIB)/hare/ast/unit.ha

$(HARECACHE)/hare/ast/hare_ast.ssa: $(stdlib_hare_ast_srcs) $(stdlib_rt) $(stdlib_hare_lex)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hare/ast
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhare::ast \
		-t$(HARECACHE)/hare/ast/hare_ast.td $(stdlib_hare_ast_srcs)

# hare::lex
stdlib_hare_lex_srcs= \
	$(STDLIB)/hare/lex/token.ha \
	$(STDLIB)/hare/lex/lex.ha

$(HARECACHE)/hare/lex/hare_lex.ssa: $(stdlib_hare_lex_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_bufio) $(stdlib_strings) $(stdlib_types) $(stdlib_fmt) $(stdlib_sort)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hare/lex
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhare::lex \
		-t$(HARECACHE)/hare/lex/hare_lex.td $(stdlib_hare_lex_srcs)

# hare::module
stdlib_hare_module_srcs= \
	$(STDLIB)/hare/module/types.ha \
	$(STDLIB)/hare/module/context.ha \
	$(STDLIB)/hare/module/scan.ha \
	$(STDLIB)/hare/module/manifest.ha

$(HARECACHE)/hare/module/hare_module.ssa: $(stdlib_hare_module_srcs) $(stdlib_rt) $(stdlib_hare_ast) $(stdlib_hare_lex) $(stdlib_hare_parse) $(stdlib_hare_unparse) $(stdlib_strio) $(stdlib_fs) $(stdlib_io) $(stdlib_strings) $(stdlib_hash) $(stdlib_crypto_sha256) $(stdlib_dirs) $(stdlib_bytes) $(stdlib_encoding_utf8) $(stdlib_ascii) $(stdlib_fmt) $(stdlib_time) $(stdlib_slice) $(stdlib_bufio) $(stdlib_strconv) $(stdlib_os) $(stdlib_encoding_hex)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hare/module
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhare::module \
		-t$(HARECACHE)/hare/module/hare_module.td $(stdlib_hare_module_srcs)

# hare::parse
stdlib_hare_parse_srcs= \
	$(STDLIB)/hare/parse/decl.ha \
	$(STDLIB)/hare/parse/expr.ha \
	$(STDLIB)/hare/parse/ident.ha \
	$(STDLIB)/hare/parse/import.ha \
	$(STDLIB)/hare/parse/type.ha \
	$(STDLIB)/hare/parse/types.ha \
	$(STDLIB)/hare/parse/unit.ha \
	$(STDLIB)/hare/parse/util.ha

$(HARECACHE)/hare/parse/hare_parse.ssa: $(stdlib_hare_parse_srcs) $(stdlib_rt) $(stdlib_hare_ast) $(stdlib_hare_lex) $(stdlib_hare_unparse) $(stdlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hare/parse
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhare::parse \
		-t$(HARECACHE)/hare/parse/hare_parse.td $(stdlib_hare_parse_srcs)

# hare::unparse
stdlib_hare_unparse_srcs= \
	$(STDLIB)/hare/unparse/expr.ha \
	$(STDLIB)/hare/unparse/decl.ha \
	$(STDLIB)/hare/unparse/ident.ha \
	$(STDLIB)/hare/unparse/import.ha \
	$(STDLIB)/hare/unparse/type.ha \
	$(STDLIB)/hare/unparse/unit.ha \
	$(STDLIB)/hare/unparse/util.ha

$(HARECACHE)/hare/unparse/hare_unparse.ssa: $(stdlib_hare_unparse_srcs) $(stdlib_rt) $(stdlib_fmt) $(stdlib_io) $(stdlib_strio) $(stdlib_hare_ast)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hare/unparse
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhare::unparse \
		-t$(HARECACHE)/hare/unparse/hare_unparse.td $(stdlib_hare_unparse_srcs)

# hash
stdlib_hash_srcs= \
	$(STDLIB)/hash/hash.ha

$(HARECACHE)/hash/hash.ssa: $(stdlib_hash_srcs) $(stdlib_rt) $(stdlib_io)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hash
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhash \
		-t$(HARECACHE)/hash/hash.td $(stdlib_hash_srcs)

# hash::adler32
stdlib_hash_adler32_srcs= \
	$(STDLIB)/hash/adler32/adler32.ha

$(HARECACHE)/hash/adler32/hash_adler32.ssa: $(stdlib_hash_adler32_srcs) $(stdlib_rt) $(stdlib_endian) $(stdlib_hash) $(stdlib_io) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hash/adler32
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhash::adler32 \
		-t$(HARECACHE)/hash/adler32/hash_adler32.td $(stdlib_hash_adler32_srcs)

# hash::fnv
stdlib_hash_fnv_srcs= \
	$(STDLIB)/hash/fnv/fnv.ha

$(HARECACHE)/hash/fnv/hash_fnv.ssa: $(stdlib_hash_fnv_srcs) $(stdlib_rt) $(stdlib_hash) $(stdlib_io) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/hash/fnv
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nhash::fnv \
		-t$(HARECACHE)/hash/fnv/hash_fnv.td $(stdlib_hash_fnv_srcs)

# io
stdlib_io_srcs= \
	$(STDLIB)/io/arch$(ARCH).ha \
	$(STDLIB)/io/copy.ha \
	$(STDLIB)/io/limit.ha \
	$(STDLIB)/io/println.ha \
	$(STDLIB)/io/stream.ha \
	$(STDLIB)/io/tee.ha \
	$(STDLIB)/io/types.ha

$(HARECACHE)/io/io.ssa: $(stdlib_io_srcs) $(stdlib_rt) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/io
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nio \
		-t$(HARECACHE)/io/io.td $(stdlib_io_srcs)

# linux
stdlib_linux_srcs= \
	$(STDLIB)/linux/start.ha \
	$(STDLIB)/linux/env.ha

$(HARECACHE)/linux/linux.ssa: $(stdlib_linux_srcs) $(stdlib_rt) $(stdlib_format_elf)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/linux
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nlinux \
		-t$(HARECACHE)/linux/linux.td $(stdlib_linux_srcs)

# linux::vdso
stdlib_linux_vdso_srcs= \
	$(STDLIB)/linux/vdso/vdso.ha

$(HARECACHE)/linux/vdso/linux_vdso.ssa: $(stdlib_linux_vdso_srcs) $(stdlib_rt) $(stdlib_linux) $(stdlib_strings) $(stdlib_format_elf)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/linux/vdso
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nlinux::vdso \
		-t$(HARECACHE)/linux/vdso/linux_vdso.td $(stdlib_linux_vdso_srcs)

# net
# net
stdlib_net_srcs= \
	$(STDLIB)/net/$(PLATFORM)/socket.ha \
	$(STDLIB)/net/$(PLATFORM)/util.ha \
	$(STDLIB)/net/socket.ha

$(HARECACHE)/net/net.ssa: $(stdlib_net_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_os) $(stdlib_strings) $(stdlib_net_ip)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/net
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nnet \
		-t$(HARECACHE)/net/net.td $(stdlib_net_srcs)

# net::ip
stdlib_net_ip_srcs= \
	$(STDLIB)/net/ip/ip.ha \
	$(STDLIB)/net/ip/$(PLATFORM).ha

$(HARECACHE)/net/ip/net_ip.ssa: $(stdlib_net_ip_srcs) $(stdlib_rt) $(stdlib_bytes) $(stdlib_io) $(stdlib_strconv) $(stdlib_strings) $(stdlib_strio) $(stdlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/net/ip
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nnet::ip \
		-t$(HARECACHE)/net/ip/net_ip.td $(stdlib_net_ip_srcs)

# math::random
stdlib_math_random_srcs= \
	$(STDLIB)/math/random/random.ha

$(HARECACHE)/math/random/math_random.ssa: $(stdlib_math_random_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/math/random
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nmath::random \
		-t$(HARECACHE)/math/random/math_random.td $(stdlib_math_random_srcs)

# os
stdlib_os_srcs= \
	$(STDLIB)/os/$(PLATFORM)/environ.ha \
	$(STDLIB)/os/$(PLATFORM)/errors.ha \
	$(STDLIB)/os/$(PLATFORM)/exit.ha \
	$(STDLIB)/os/$(PLATFORM)/dirfdfs.ha \
	$(STDLIB)/os/$(PLATFORM)/fdstream.ha \
	$(STDLIB)/os/$(PLATFORM)/open.ha \
	$(STDLIB)/os/$(PLATFORM)/stdfd.ha \
	$(STDLIB)/os/$(PLATFORM)/fs.ha \
	$(STDLIB)/os/stdfd.ha \
	$(STDLIB)/os/fs.ha

$(HARECACHE)/os/os.ssa: $(stdlib_os_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_strings) $(stdlib_types) $(stdlib_fs) $(stdlib_encoding_utf8) $(stdlib_bytes) $(stdlib_bufio)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/os
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nos \
		-t$(HARECACHE)/os/os.td $(stdlib_os_srcs)

# os::exec
stdlib_os_exec_srcs= \
	$(STDLIB)/os/exec/$(PLATFORM).ha \
	$(STDLIB)/os/exec/exec$(PLATFORM).ha \
	$(STDLIB)/os/exec/process$(PLATFORM).ha \
	$(STDLIB)/os/exec/types.ha \
	$(STDLIB)/os/exec/cmd.ha

$(HARECACHE)/os/exec/os_exec.ssa: $(stdlib_os_exec_srcs) $(stdlib_rt) $(stdlib_os) $(stdlib_strings) $(stdlib_fmt) $(stdlib_bytes) $(stdlib_path)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/os/exec
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nos::exec \
		-t$(HARECACHE)/os/exec/os_exec.td $(stdlib_os_exec_srcs)

# path
stdlib_path_srcs= \
	$(STDLIB)/path/$(PLATFORM).ha \
	$(STDLIB)/path/util.ha \
	$(STDLIB)/path/join.ha \
	$(STDLIB)/path/names.ha \
	$(STDLIB)/path/iter.ha

$(HARECACHE)/path/path.ssa: $(stdlib_path_srcs) $(stdlib_rt) $(stdlib_strings) $(stdlib_bufio) $(stdlib_bytes)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/path
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Npath \
		-t$(HARECACHE)/path/path.td $(stdlib_path_srcs)

# slice
stdlib_slice_srcs= \
	$(STDLIB)/slice/reverse.ha

$(HARECACHE)/slice/slice.ssa: $(stdlib_slice_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/slice
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nslice \
		-t$(HARECACHE)/slice/slice.td $(stdlib_slice_srcs)

# sort
stdlib_sort_srcs= \
	$(STDLIB)/sort/search.ha

$(HARECACHE)/sort/sort.ssa: $(stdlib_sort_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/sort
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nsort \
		-t$(HARECACHE)/sort/sort.td $(stdlib_sort_srcs)

# strconv
stdlib_strconv_srcs= \
	$(STDLIB)/strconv/types.ha \
	$(STDLIB)/strconv/itos.ha \
	$(STDLIB)/strconv/utos.ha \
	$(STDLIB)/strconv/stou.ha \
	$(STDLIB)/strconv/stoi.ha \
	$(STDLIB)/strconv/numeric.ha

$(HARECACHE)/strconv/strconv.ssa: $(stdlib_strconv_srcs) $(stdlib_rt) $(stdlib_types) $(stdlib_strings) $(stdlib_ascii)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/strconv
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nstrconv \
		-t$(HARECACHE)/strconv/strconv.td $(stdlib_strconv_srcs)

# strings
stdlib_strings_srcs= \
	$(STDLIB)/strings/concat.ha \
	$(STDLIB)/strings/contains.ha \
	$(STDLIB)/strings/cstrings.ha \
	$(STDLIB)/strings/dup.ha \
	$(STDLIB)/strings/iter.ha \
	$(STDLIB)/strings/sub.ha \
	$(STDLIB)/strings/suffix.ha \
	$(STDLIB)/strings/tokenize.ha \
	$(STDLIB)/strings/utf8.ha \
	$(STDLIB)/strings/index.ha

$(HARECACHE)/strings/strings.ssa: $(stdlib_strings_srcs) $(stdlib_rt) $(stdlib_bytes) $(stdlib_encoding_utf8) $(stdlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/strings
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nstrings \
		-t$(HARECACHE)/strings/strings.td $(stdlib_strings_srcs)

# strio
stdlib_strio_srcs= \
	$(STDLIB)/strio/dynamic.ha \
	$(STDLIB)/strio/fixed.ha \
	$(STDLIB)/strio/ops.ha

$(HARECACHE)/strio/strio.ssa: $(stdlib_strio_srcs) $(stdlib_rt) $(stdlib_io) $(stdlib_strings) $(stdlib_encoding_utf8)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/strio
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nstrio \
		-t$(HARECACHE)/strio/strio.td $(stdlib_strio_srcs)

# temp
stdlib_temp_srcs= \
	$(STDLIB)/temp/$(PLATFORM).ha

$(HARECACHE)/temp/temp.ssa: $(stdlib_temp_srcs) $(stdlib_rt) $(stdlib_crypto_random) $(stdlib_encoding_hex) $(stdlib_fs) $(stdlib_io) $(stdlib_os) $(stdlib_path) $(stdlib_strio)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/temp
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ntemp \
		-t$(HARECACHE)/temp/temp.td $(stdlib_temp_srcs)

# time
stdlib_time_srcs= \
	$(STDLIB)/time/$(PLATFORM)/functions.ha \
	$(STDLIB)/time/$(PLATFORM)/$(ARCH).ha \
	$(STDLIB)/time/types.ha

$(HARECACHE)/time/time.ssa: $(stdlib_time_srcs) $(stdlib_rt) $(stdlib_linux_vdso)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/time
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ntime \
		-t$(HARECACHE)/time/time.td $(stdlib_time_srcs)

# types
stdlib_types_srcs= \
	$(STDLIB)/types/limits.ha \
	$(STDLIB)/types/classes.ha \
	$(STDLIB)/types/arch$(ARCH).ha

$(HARECACHE)/types/types.ssa: $(stdlib_types_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/types
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Ntypes \
		-t$(HARECACHE)/types/types.td $(stdlib_types_srcs)

# unicode
stdlib_unicode_srcs= \
	$(STDLIB)/unicode/properties.ha \
	$(STDLIB)/unicode/unicode.ha

$(HARECACHE)/unicode/unicode.ssa: $(stdlib_unicode_srcs) $(stdlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/unicode
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nunicode \
		-t$(HARECACHE)/unicode/unicode.td $(stdlib_unicode_srcs)

# unix::passwd
stdlib_unix_passwd_srcs= \
	$(STDLIB)/unix/passwd/passwd.ha

$(HARECACHE)/unix/passwd/unix_passwd.ssa: $(stdlib_unix_passwd_srcs) $(stdlib_rt) $(stdlib_bufio) $(stdlib_io) $(stdlib_os) $(stdlib_strconv) $(stdlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/unix/passwd
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nunix::passwd \
		-t$(HARECACHE)/unix/passwd/unix_passwd.td $(stdlib_unix_passwd_srcs)

# uuid
stdlib_uuid_srcs= \
	$(STDLIB)/uuid/uuid.ha

$(HARECACHE)/uuid/uuid.ssa: $(stdlib_uuid_srcs) $(stdlib_rt) $(stdlib_crypto_random) $(stdlib_strio) $(stdlib_fmt) $(stdlib_endian) $(stdlib_io) $(stdlib_bytes)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(HARECACHE)/uuid
	@HARECACHE=$(HARECACHE) $(HAREC) $(HAREFLAGS) -o $@ -Nuuid \
		-t$(HARECACHE)/uuid/uuid.td $(stdlib_uuid_srcs)

# rt
testlib_rt_srcs= \
	$(STDLIB)/rt/$(PLATFORM)/abort.ha \
	$(STDLIB)/rt/$(PLATFORM)/env.ha \
	$(STDLIB)/rt/$(PLATFORM)/errno.ha \
	$(STDLIB)/rt/$(PLATFORM)/types.ha \
	$(STDLIB)/rt/$(PLATFORM)/segmalloc.ha \
	$(STDLIB)/rt/$(PLATFORM)/start.ha \
	$(STDLIB)/rt/$(PLATFORM)/$(ARCH).ha \
	$(STDLIB)/rt/$(PLATFORM)/syscallno$(ARCH).ha \
	$(STDLIB)/rt/$(PLATFORM)/syscalls.ha \
	$(STDLIB)/rt/$(PLATFORM)/signal.ha \
	$(STDLIB)/rt/$(PLATFORM)/stat.ha \
	$(STDLIB)/rt/$(PLATFORM)/socket.ha \
	$(STDLIB)/rt/$(ARCH)/jmp.ha \
	$(STDLIB)/rt/ensure.ha \
	$(STDLIB)/rt/jmp.ha \
	$(STDLIB)/rt/malloc.ha \
	$(STDLIB)/rt/memcpy.ha \
	$(STDLIB)/rt/memset.ha \
	$(STDLIB)/rt/strcmp.ha \
	$(STDLIB)/rt/start+test.ha \
	$(STDLIB)/rt/abort+test.ha \
	$(STDLIB)/rt/+test/$(PLATFORM).ha \
	$(STDLIB)/rt/+test/cstring.ha \
	$(STDLIB)/rt/+test/run.ha \
	$(STDLIB)/rt/+test/ztos.ha

$(TESTCACHE)/rt/rt.ssa: $(testlib_rt_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/rt
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nrt \
		-t$(TESTCACHE)/rt/rt.td $(testlib_rt_srcs)

$(TESTCACHE)/rt/start.o: $(STDLIB)/rt/$(PLATFORM)/start$(ARCH).s
	@printf 'AS \t$@\n'
	@mkdir -p $(TESTCACHE)/rt
	@$(AS) -o $@ $<

testlib_asm=$(TESTCACHE)/rt/syscall.o \
	$(TESTCACHE)/rt/setjmp.o \
	$(TESTCACHE)/rt/longjmp.o \
	$(TESTCACHE)/rt/restore.o \
	$(TESTCACHE)/rt/start.o

$(TESTCACHE)/rt/syscall.o: $(STDLIB)/rt/$(PLATFORM)/syscall$(ARCH).s
	@printf 'AS \t$@\n'
	@mkdir -p $(TESTCACHE)/rt
	@$(AS) -o $@ $<

$(TESTCACHE)/rt/setjmp.o: $(STDLIB)/rt/$(ARCH)/setjmp.s
	@printf 'AS \t$@\n'
	@mkdir -p $(TESTCACHE)/rt
	@$(AS) -o $@ $<

$(TESTCACHE)/rt/longjmp.o: $(STDLIB)/rt/$(ARCH)/longjmp.s
	@printf 'AS \t$@\n'
	@mkdir -p $(TESTCACHE)/rt
	@$(AS) -o $@ $<

$(TESTCACHE)/rt/restore.o: $(STDLIB)/rt/$(ARCH)/restore.s
	@printf 'AS \t$@\n'
	@mkdir -p $(TESTCACHE)/rt
	@$(AS) -o $@ $<

$(TESTCACHE)/rt/rt.a: $(TESTCACHE)/rt/rt.o $(testlib_asm)
	@printf 'AR\t$@\n'
	@$(AR) -csr $@ $(TESTCACHE)/rt/rt.o $(testlib_asm)

testlib_rt=$(TESTCACHE)/rt/rt.a
hare_testlib_deps+=$(testlib_rt)

testlib_ascii=$(TESTCACHE)/ascii/ascii.o
hare_testlib_deps+=$(testlib_ascii)

testlib_bufio=$(TESTCACHE)/bufio/bufio.o
hare_testlib_deps+=$(testlib_bufio)

testlib_bytes=$(TESTCACHE)/bytes/bytes.o
hare_testlib_deps+=$(testlib_bytes)

testlib_crypto_math=$(TESTCACHE)/crypto/math/crypto_math.o
hare_testlib_deps+=$(testlib_crypto_math)

testlib_crypto_random=$(TESTCACHE)/crypto/random/crypto_random.o
hare_testlib_deps+=$(testlib_crypto_random)

testlib_crypto_sha1=$(TESTCACHE)/crypto/sha1/crypto_sha1.o
hare_testlib_deps+=$(testlib_crypto_sha1)

testlib_crypto_sha256=$(TESTCACHE)/crypto/sha256/crypto_sha256.o
hare_testlib_deps+=$(testlib_crypto_sha256)

testlib_crypto_sha512=$(TESTCACHE)/crypto/sha512/crypto_sha512.o
hare_testlib_deps+=$(testlib_crypto_sha512)

testlib_dirs=$(TESTCACHE)/dirs/dirs.o
hare_testlib_deps+=$(testlib_dirs)

testlib_encoding_hex=$(TESTCACHE)/encoding/hex/encoding_hex.o
hare_testlib_deps+=$(testlib_encoding_hex)

testlib_encoding_utf8=$(TESTCACHE)/encoding/utf8/encoding_utf8.o
hare_testlib_deps+=$(testlib_encoding_utf8)

testlib_endian=$(TESTCACHE)/endian/endian.o
hare_testlib_deps+=$(testlib_endian)

testlib_fmt=$(TESTCACHE)/fmt/fmt.o
hare_testlib_deps+=$(testlib_fmt)

testlib_format_elf=$(TESTCACHE)/format/elf/format_elf.o
hare_testlib_deps+=$(testlib_format_elf)

testlib_fs=$(TESTCACHE)/fs/fs.o
hare_testlib_deps+=$(testlib_fs)

testlib_getopt=$(TESTCACHE)/getopt/getopt.o
hare_testlib_deps+=$(testlib_getopt)

testlib_hare_ast=$(TESTCACHE)/hare/ast/hare_ast.o
hare_testlib_deps+=$(testlib_hare_ast)

testlib_hare_lex=$(TESTCACHE)/hare/lex/hare_lex.o
hare_testlib_deps+=$(testlib_hare_lex)

testlib_hare_module=$(TESTCACHE)/hare/module/hare_module.o
hare_testlib_deps+=$(testlib_hare_module)

testlib_hare_parse=$(TESTCACHE)/hare/parse/hare_parse.o
hare_testlib_deps+=$(testlib_hare_parse)

testlib_hare_unparse=$(TESTCACHE)/hare/unparse/hare_unparse.o
hare_testlib_deps+=$(testlib_hare_unparse)

testlib_hash=$(TESTCACHE)/hash/hash.o
hare_testlib_deps+=$(testlib_hash)

testlib_hash_adler32=$(TESTCACHE)/hash/adler32/hash_adler32.o
hare_testlib_deps+=$(testlib_hash_adler32)

testlib_hash_fnv=$(TESTCACHE)/hash/fnv/hash_fnv.o
hare_testlib_deps+=$(testlib_hash_fnv)

testlib_io=$(TESTCACHE)/io/io.o
hare_testlib_deps+=$(testlib_io)

testlib_linux=$(TESTCACHE)/linux/linux.o
hare_testlib_deps+=$(testlib_linux)

testlib_linux_vdso=$(TESTCACHE)/linux/vdso/linux_vdso.o
hare_testlib_deps+=$(testlib_linux_vdso)

testlib_net=$(TESTCACHE)/net/net.o
hare_testlib_deps+=$(testlib_net)

testlib_net_ip=$(TESTCACHE)/net/ip/net_ip.o
hare_testlib_deps+=$(testlib_net_ip)

testlib_math_random=$(TESTCACHE)/math/random/math_random.o
hare_testlib_deps+=$(testlib_math_random)

testlib_os=$(TESTCACHE)/os/os.o
hare_testlib_deps+=$(testlib_os)

testlib_os_exec=$(TESTCACHE)/os/exec/os_exec.o
hare_testlib_deps+=$(testlib_os_exec)

testlib_path=$(TESTCACHE)/path/path.o
hare_testlib_deps+=$(testlib_path)

testlib_slice=$(TESTCACHE)/slice/slice.o
hare_testlib_deps+=$(testlib_slice)

testlib_sort=$(TESTCACHE)/sort/sort.o
hare_testlib_deps+=$(testlib_sort)

testlib_strconv=$(TESTCACHE)/strconv/strconv.o
hare_testlib_deps+=$(testlib_strconv)

testlib_strings=$(TESTCACHE)/strings/strings.o
hare_testlib_deps+=$(testlib_strings)

testlib_strio=$(TESTCACHE)/strio/strio.o
hare_testlib_deps+=$(testlib_strio)

testlib_temp=$(TESTCACHE)/temp/temp.o
hare_testlib_deps+=$(testlib_temp)

testlib_time=$(TESTCACHE)/time/time.o
hare_testlib_deps+=$(testlib_time)

testlib_types=$(TESTCACHE)/types/types.o
hare_testlib_deps+=$(testlib_types)

testlib_unicode=$(TESTCACHE)/unicode/unicode.o
hare_testlib_deps+=$(testlib_unicode)

testlib_unix_passwd=$(TESTCACHE)/unix/passwd/unix_passwd.o
hare_testlib_deps+=$(testlib_unix_passwd)

testlib_uuid=$(TESTCACHE)/uuid/uuid.o
hare_testlib_deps+=$(testlib_uuid)

# ascii
testlib_ascii_srcs= \
	$(STDLIB)/ascii/ctype.ha \
	$(STDLIB)/ascii/strcmp.ha

$(TESTCACHE)/ascii/ascii.ssa: $(testlib_ascii_srcs) $(testlib_rt) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/ascii
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nascii \
		-t$(TESTCACHE)/ascii/ascii.td $(testlib_ascii_srcs)

# bufio
testlib_bufio_srcs= \
	$(STDLIB)/bufio/buffered.ha \
	$(STDLIB)/bufio/dynamic.ha \
	$(STDLIB)/bufio/fixed.ha \
	$(STDLIB)/bufio/scanner.ha

$(TESTCACHE)/bufio/bufio.ssa: $(testlib_bufio_srcs) $(testlib_rt) $(testlib_io) $(testlib_bytes) $(testlib_strings) $(testlib_encoding_utf8)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/bufio
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nbufio \
		-t$(TESTCACHE)/bufio/bufio.td $(testlib_bufio_srcs)

# bytes
testlib_bytes_srcs= \
	$(STDLIB)/bytes/contains.ha \
	$(STDLIB)/bytes/copy.ha \
	$(STDLIB)/bytes/equal.ha \
	$(STDLIB)/bytes/index.ha \
	$(STDLIB)/bytes/reverse.ha \
	$(STDLIB)/bytes/tokenize.ha

$(TESTCACHE)/bytes/bytes.ssa: $(testlib_bytes_srcs) $(testlib_rt) $(testlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/bytes
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nbytes \
		-t$(TESTCACHE)/bytes/bytes.td $(testlib_bytes_srcs)

# crypto::math
testlib_crypto_math_srcs= \
	$(STDLIB)/crypto/math/bits.ha

$(TESTCACHE)/crypto/math/crypto_math.ssa: $(testlib_crypto_math_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/crypto/math
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ncrypto::math \
		-t$(TESTCACHE)/crypto/math/crypto_math.td $(testlib_crypto_math_srcs)

# crypto::random
testlib_crypto_random_srcs= \
	$(STDLIB)/crypto/random/$(PLATFORM).ha \
	$(STDLIB)/crypto/random/random.ha

$(TESTCACHE)/crypto/random/crypto_random.ssa: $(testlib_crypto_random_srcs) $(testlib_rt) $(testlib_rt) $(testlib_io)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/crypto/random
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ncrypto::random \
		-t$(TESTCACHE)/crypto/random/crypto_random.td $(testlib_crypto_random_srcs)

# crypto::sha1
testlib_crypto_sha1_srcs= \
	$(STDLIB)/crypto/sha1/sha1.ha \
	$(STDLIB)/crypto/sha1/+test.ha

$(TESTCACHE)/crypto/sha1/crypto_sha1.ssa: $(testlib_crypto_sha1_srcs) $(testlib_rt) $(testlib_hash) $(testlib_io) $(testlib_endian) $(testlib_fmt) $(testlib_strio) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/crypto/sha1
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ncrypto::sha1 \
		-t$(TESTCACHE)/crypto/sha1/crypto_sha1.td $(testlib_crypto_sha1_srcs)

# crypto::sha256
testlib_crypto_sha256_srcs= \
	$(STDLIB)/crypto/sha256/sha256.ha \
	$(STDLIB)/crypto/sha256/+test.ha

$(TESTCACHE)/crypto/sha256/crypto_sha256.ssa: $(testlib_crypto_sha256_srcs) $(testlib_rt) $(testlib_hash) $(testlib_io) $(testlib_endian) $(testlib_fmt) $(testlib_strio) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/crypto/sha256
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ncrypto::sha256 \
		-t$(TESTCACHE)/crypto/sha256/crypto_sha256.td $(testlib_crypto_sha256_srcs)

# crypto::sha512
testlib_crypto_sha512_srcs= \
	$(STDLIB)/crypto/sha512/sha512.ha \
	$(STDLIB)/crypto/sha512/+test.ha

$(TESTCACHE)/crypto/sha512/crypto_sha512.ssa: $(testlib_crypto_sha512_srcs) $(testlib_rt) $(testlib_hash) $(testlib_io) $(testlib_endian) $(testlib_fmt) $(testlib_strio) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/crypto/sha512
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ncrypto::sha512 \
		-t$(TESTCACHE)/crypto/sha512/crypto_sha512.td $(testlib_crypto_sha512_srcs)

# dirs
testlib_dirs_srcs= \
	$(STDLIB)/dirs/xdg.ha

$(TESTCACHE)/dirs/dirs.ssa: $(testlib_dirs_srcs) $(testlib_rt) $(testlib_fs) $(testlib_os) $(testlib_path)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/dirs
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ndirs \
		-t$(TESTCACHE)/dirs/dirs.td $(testlib_dirs_srcs)

# encoding::hex
testlib_encoding_hex_srcs= \
	$(STDLIB)/encoding/hex/hex.ha

$(TESTCACHE)/encoding/hex/encoding_hex.ssa: $(testlib_encoding_hex_srcs) $(testlib_rt) $(testlib_ascii) $(testlib_bytes) $(testlib_fmt) $(testlib_io) $(testlib_strconv) $(testlib_strio) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/encoding/hex
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nencoding::hex \
		-t$(TESTCACHE)/encoding/hex/encoding_hex.td $(testlib_encoding_hex_srcs)

# encoding::utf8
testlib_encoding_utf8_srcs= \
	$(STDLIB)/encoding/utf8/decode.ha \
	$(STDLIB)/encoding/utf8/encode.ha \
	$(STDLIB)/encoding/utf8/rune.ha

$(TESTCACHE)/encoding/utf8/encoding_utf8.ssa: $(testlib_encoding_utf8_srcs) $(testlib_rt) $(testlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/encoding/utf8
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nencoding::utf8 \
		-t$(TESTCACHE)/encoding/utf8/encoding_utf8.td $(testlib_encoding_utf8_srcs)

# endian
testlib_endian_srcs= \
	$(STDLIB)/endian/big.ha \
	$(STDLIB)/endian/network.ha \
	$(STDLIB)/endian/little.ha \
	$(STDLIB)/endian/endian.ha \
	$(STDLIB)/endian/host$(ARCH).ha

$(TESTCACHE)/endian/endian.ssa: $(testlib_endian_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/endian
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nendian \
		-t$(TESTCACHE)/endian/endian.td $(testlib_endian_srcs)

# fmt
testlib_fmt_srcs= \
	$(STDLIB)/fmt/fmt.ha

$(TESTCACHE)/fmt/fmt.ssa: $(testlib_fmt_srcs) $(testlib_rt) $(testlib_bufio) $(testlib_io) $(testlib_os) $(testlib_strconv) $(testlib_strings) $(testlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/fmt
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nfmt \
		-t$(TESTCACHE)/fmt/fmt.td $(testlib_fmt_srcs)

# format::elf
testlib_format_elf_srcs= \
	$(STDLIB)/format/elf/types.ha

$(TESTCACHE)/format/elf/format_elf.ssa: $(testlib_format_elf_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/format/elf
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nformat::elf \
		-t$(TESTCACHE)/format/elf/format_elf.td $(testlib_format_elf_srcs)

# fs
testlib_fs_srcs= \
	$(STDLIB)/fs/types.ha \
	$(STDLIB)/fs/fs.ha \
	$(STDLIB)/fs/util.ha

$(TESTCACHE)/fs/fs.ssa: $(testlib_fs_srcs) $(testlib_rt) $(testlib_io) $(testlib_strings) $(testlib_path) $(testlib_time)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/fs
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nfs \
		-t$(TESTCACHE)/fs/fs.td $(testlib_fs_srcs)

# getopt
testlib_getopt_srcs= \
	$(STDLIB)/getopt/getopts.ha

$(TESTCACHE)/getopt/getopt.ssa: $(testlib_getopt_srcs) $(testlib_rt) $(testlib_encoding_utf8) $(testlib_fmt) $(testlib_io) $(testlib_os) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/getopt
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ngetopt \
		-t$(TESTCACHE)/getopt/getopt.td $(testlib_getopt_srcs)

# hare::ast
testlib_hare_ast_srcs= \
	$(STDLIB)/hare/ast/decl.ha \
	$(STDLIB)/hare/ast/expr.ha \
	$(STDLIB)/hare/ast/ident.ha \
	$(STDLIB)/hare/ast/import.ha \
	$(STDLIB)/hare/ast/type.ha \
	$(STDLIB)/hare/ast/unit.ha

$(TESTCACHE)/hare/ast/hare_ast.ssa: $(testlib_hare_ast_srcs) $(testlib_rt) $(testlib_hare_lex)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hare/ast
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhare::ast \
		-t$(TESTCACHE)/hare/ast/hare_ast.td $(testlib_hare_ast_srcs)

# hare::lex
testlib_hare_lex_srcs= \
	$(STDLIB)/hare/lex/token.ha \
	$(STDLIB)/hare/lex/lex.ha \
	$(STDLIB)/hare/lex/+test.ha

$(TESTCACHE)/hare/lex/hare_lex.ssa: $(testlib_hare_lex_srcs) $(testlib_rt) $(testlib_io) $(testlib_bufio) $(testlib_strings) $(testlib_types) $(testlib_fmt) $(testlib_sort)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hare/lex
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhare::lex \
		-t$(TESTCACHE)/hare/lex/hare_lex.td $(testlib_hare_lex_srcs)

# hare::module
testlib_hare_module_srcs= \
	$(STDLIB)/hare/module/types.ha \
	$(STDLIB)/hare/module/context.ha \
	$(STDLIB)/hare/module/scan.ha \
	$(STDLIB)/hare/module/manifest.ha

$(TESTCACHE)/hare/module/hare_module.ssa: $(testlib_hare_module_srcs) $(testlib_rt) $(testlib_hare_ast) $(testlib_hare_lex) $(testlib_hare_parse) $(testlib_hare_unparse) $(testlib_strio) $(testlib_fs) $(testlib_io) $(testlib_strings) $(testlib_hash) $(testlib_crypto_sha256) $(testlib_dirs) $(testlib_bytes) $(testlib_encoding_utf8) $(testlib_ascii) $(testlib_fmt) $(testlib_time) $(testlib_slice) $(testlib_bufio) $(testlib_strconv) $(testlib_os) $(testlib_encoding_hex)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hare/module
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhare::module \
		-t$(TESTCACHE)/hare/module/hare_module.td $(testlib_hare_module_srcs)

# hare::parse
testlib_hare_parse_srcs= \
	$(STDLIB)/hare/parse/decl.ha \
	$(STDLIB)/hare/parse/expr.ha \
	$(STDLIB)/hare/parse/ident.ha \
	$(STDLIB)/hare/parse/import.ha \
	$(STDLIB)/hare/parse/type.ha \
	$(STDLIB)/hare/parse/types.ha \
	$(STDLIB)/hare/parse/unit.ha \
	$(STDLIB)/hare/parse/util.ha \
	$(STDLIB)/hare/parse/+test.ha

$(TESTCACHE)/hare/parse/hare_parse.ssa: $(testlib_hare_parse_srcs) $(testlib_rt) $(testlib_bufio) $(testlib_fmt) $(testlib_hare_ast) $(testlib_hare_lex) $(testlib_hare_unparse) $(testlib_io) $(testlib_strings) $(testlib_strio) $(testlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hare/parse
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhare::parse \
		-t$(TESTCACHE)/hare/parse/hare_parse.td $(testlib_hare_parse_srcs)

# hare::unparse
testlib_hare_unparse_srcs= \
	$(STDLIB)/hare/unparse/expr.ha \
	$(STDLIB)/hare/unparse/decl.ha \
	$(STDLIB)/hare/unparse/ident.ha \
	$(STDLIB)/hare/unparse/import.ha \
	$(STDLIB)/hare/unparse/type.ha \
	$(STDLIB)/hare/unparse/unit.ha \
	$(STDLIB)/hare/unparse/util.ha

$(TESTCACHE)/hare/unparse/hare_unparse.ssa: $(testlib_hare_unparse_srcs) $(testlib_rt) $(testlib_fmt) $(testlib_io) $(testlib_strio) $(testlib_hare_ast)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hare/unparse
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhare::unparse \
		-t$(TESTCACHE)/hare/unparse/hare_unparse.td $(testlib_hare_unparse_srcs)

# hash
testlib_hash_srcs= \
	$(STDLIB)/hash/hash.ha

$(TESTCACHE)/hash/hash.ssa: $(testlib_hash_srcs) $(testlib_rt) $(testlib_io)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hash
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhash \
		-t$(TESTCACHE)/hash/hash.td $(testlib_hash_srcs)

# hash::adler32
testlib_hash_adler32_srcs= \
	$(STDLIB)/hash/adler32/adler32.ha

$(TESTCACHE)/hash/adler32/hash_adler32.ssa: $(testlib_hash_adler32_srcs) $(testlib_rt) $(testlib_endian) $(testlib_hash) $(testlib_io) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hash/adler32
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhash::adler32 \
		-t$(TESTCACHE)/hash/adler32/hash_adler32.td $(testlib_hash_adler32_srcs)

# hash::fnv
testlib_hash_fnv_srcs= \
	$(STDLIB)/hash/fnv/fnv.ha

$(TESTCACHE)/hash/fnv/hash_fnv.ssa: $(testlib_hash_fnv_srcs) $(testlib_rt) $(testlib_hash) $(testlib_io) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/hash/fnv
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nhash::fnv \
		-t$(TESTCACHE)/hash/fnv/hash_fnv.td $(testlib_hash_fnv_srcs)

# io
testlib_io_srcs= \
	$(STDLIB)/io/arch$(ARCH).ha \
	$(STDLIB)/io/copy.ha \
	$(STDLIB)/io/limit.ha \
	$(STDLIB)/io/println.ha \
	$(STDLIB)/io/stream.ha \
	$(STDLIB)/io/tee.ha \
	$(STDLIB)/io/types.ha \
	$(STDLIB)/io/+test/copy.ha \
	$(STDLIB)/io/+test/limit.ha \
	$(STDLIB)/io/+test/stream.ha

$(TESTCACHE)/io/io.ssa: $(testlib_io_srcs) $(testlib_rt) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/io
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nio \
		-t$(TESTCACHE)/io/io.td $(testlib_io_srcs)

# linux
testlib_linux_srcs= \
	$(STDLIB)/linux/start.ha \
	$(STDLIB)/linux/env.ha

$(TESTCACHE)/linux/linux.ssa: $(testlib_linux_srcs) $(testlib_rt) $(testlib_format_elf)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/linux
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nlinux \
		-t$(TESTCACHE)/linux/linux.td $(testlib_linux_srcs)

# linux::vdso
testlib_linux_vdso_srcs= \
	$(STDLIB)/linux/vdso/vdso.ha

$(TESTCACHE)/linux/vdso/linux_vdso.ssa: $(testlib_linux_vdso_srcs) $(testlib_rt) $(testlib_linux) $(testlib_strings) $(testlib_format_elf)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/linux/vdso
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nlinux::vdso \
		-t$(TESTCACHE)/linux/vdso/linux_vdso.td $(testlib_linux_vdso_srcs)

# net
# net
testlib_net_srcs= \
	$(STDLIB)/net/$(PLATFORM)/socket.ha \
	$(STDLIB)/net/$(PLATFORM)/util.ha \
	$(STDLIB)/net/socket.ha

$(TESTCACHE)/net/net.ssa: $(testlib_net_srcs) $(testlib_rt) $(testlib_io) $(testlib_os) $(testlib_strings) $(testlib_net_ip)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/net
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nnet \
		-t$(TESTCACHE)/net/net.td $(testlib_net_srcs)

# net::ip
testlib_net_ip_srcs= \
	$(STDLIB)/net/ip/ip.ha \
	$(STDLIB)/net/ip/$(PLATFORM).ha \
	$(STDLIB)/net/ip/+test.ha

$(TESTCACHE)/net/ip/net_ip.ssa: $(testlib_net_ip_srcs) $(testlib_rt) $(testlib_bytes) $(testlib_io) $(testlib_strconv) $(testlib_strings) $(testlib_strio) $(testlib_fmt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/net/ip
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nnet::ip \
		-t$(TESTCACHE)/net/ip/net_ip.td $(testlib_net_ip_srcs)

# math::random
testlib_math_random_srcs= \
	$(STDLIB)/math/random/random.ha

$(TESTCACHE)/math/random/math_random.ssa: $(testlib_math_random_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/math/random
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nmath::random \
		-t$(TESTCACHE)/math/random/math_random.td $(testlib_math_random_srcs)

# os
testlib_os_srcs= \
	$(STDLIB)/os/$(PLATFORM)/environ.ha \
	$(STDLIB)/os/$(PLATFORM)/errors.ha \
	$(STDLIB)/os/$(PLATFORM)/exit.ha \
	$(STDLIB)/os/$(PLATFORM)/dirfdfs.ha \
	$(STDLIB)/os/$(PLATFORM)/fdstream.ha \
	$(STDLIB)/os/$(PLATFORM)/open.ha \
	$(STDLIB)/os/$(PLATFORM)/stdfd.ha \
	$(STDLIB)/os/$(PLATFORM)/fs.ha \
	$(STDLIB)/os/stdfd.ha \
	$(STDLIB)/os/fs.ha

$(TESTCACHE)/os/os.ssa: $(testlib_os_srcs) $(testlib_rt) $(testlib_io) $(testlib_strings) $(testlib_types) $(testlib_fs) $(testlib_encoding_utf8) $(testlib_bytes) $(testlib_bufio)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/os
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nos \
		-t$(TESTCACHE)/os/os.td $(testlib_os_srcs)

# os::exec
testlib_os_exec_srcs= \
	$(STDLIB)/os/exec/$(PLATFORM).ha \
	$(STDLIB)/os/exec/exec$(PLATFORM).ha \
	$(STDLIB)/os/exec/process$(PLATFORM).ha \
	$(STDLIB)/os/exec/types.ha \
	$(STDLIB)/os/exec/cmd.ha

$(TESTCACHE)/os/exec/os_exec.ssa: $(testlib_os_exec_srcs) $(testlib_rt) $(testlib_os) $(testlib_strings) $(testlib_fmt) $(testlib_bytes) $(testlib_path)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/os/exec
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nos::exec \
		-t$(TESTCACHE)/os/exec/os_exec.td $(testlib_os_exec_srcs)

# path
testlib_path_srcs= \
	$(STDLIB)/path/$(PLATFORM).ha \
	$(STDLIB)/path/util.ha \
	$(STDLIB)/path/join.ha \
	$(STDLIB)/path/names.ha \
	$(STDLIB)/path/iter.ha

$(TESTCACHE)/path/path.ssa: $(testlib_path_srcs) $(testlib_rt) $(testlib_strings) $(testlib_bufio) $(testlib_bytes)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/path
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Npath \
		-t$(TESTCACHE)/path/path.td $(testlib_path_srcs)

# slice
testlib_slice_srcs= \
	$(STDLIB)/slice/reverse.ha

$(TESTCACHE)/slice/slice.ssa: $(testlib_slice_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/slice
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nslice \
		-t$(TESTCACHE)/slice/slice.td $(testlib_slice_srcs)

# sort
testlib_sort_srcs= \
	$(STDLIB)/sort/search.ha \
	$(STDLIB)/sort/+test.ha

$(TESTCACHE)/sort/sort.ssa: $(testlib_sort_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/sort
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nsort \
		-t$(TESTCACHE)/sort/sort.td $(testlib_sort_srcs)

# strconv
testlib_strconv_srcs= \
	$(STDLIB)/strconv/types.ha \
	$(STDLIB)/strconv/itos.ha \
	$(STDLIB)/strconv/utos.ha \
	$(STDLIB)/strconv/stou.ha \
	$(STDLIB)/strconv/stoi.ha \
	$(STDLIB)/strconv/numeric.ha \
	$(STDLIB)/strconv/+test/stou.ha \
	$(STDLIB)/strconv/+test/stoi.ha

$(TESTCACHE)/strconv/strconv.ssa: $(testlib_strconv_srcs) $(testlib_rt) $(testlib_types) $(testlib_strings) $(testlib_ascii)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/strconv
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nstrconv \
		-t$(TESTCACHE)/strconv/strconv.td $(testlib_strconv_srcs)

# strings
testlib_strings_srcs= \
	$(STDLIB)/strings/concat.ha \
	$(STDLIB)/strings/contains.ha \
	$(STDLIB)/strings/cstrings.ha \
	$(STDLIB)/strings/dup.ha \
	$(STDLIB)/strings/iter.ha \
	$(STDLIB)/strings/sub.ha \
	$(STDLIB)/strings/suffix.ha \
	$(STDLIB)/strings/tokenize.ha \
	$(STDLIB)/strings/utf8.ha \
	$(STDLIB)/strings/index.ha

$(TESTCACHE)/strings/strings.ssa: $(testlib_strings_srcs) $(testlib_rt) $(testlib_bytes) $(testlib_encoding_utf8) $(testlib_types)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/strings
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nstrings \
		-t$(TESTCACHE)/strings/strings.td $(testlib_strings_srcs)

# strio
testlib_strio_srcs= \
	$(STDLIB)/strio/dynamic.ha \
	$(STDLIB)/strio/fixed.ha \
	$(STDLIB)/strio/ops.ha

$(TESTCACHE)/strio/strio.ssa: $(testlib_strio_srcs) $(testlib_rt) $(testlib_io) $(testlib_strings) $(testlib_encoding_utf8)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/strio
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nstrio \
		-t$(TESTCACHE)/strio/strio.td $(testlib_strio_srcs)

# temp
testlib_temp_srcs= \
	$(STDLIB)/temp/$(PLATFORM).ha

$(TESTCACHE)/temp/temp.ssa: $(testlib_temp_srcs) $(testlib_rt) $(testlib_crypto_random) $(testlib_encoding_hex) $(testlib_fs) $(testlib_io) $(testlib_os) $(testlib_path) $(testlib_strio)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/temp
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ntemp \
		-t$(TESTCACHE)/temp/temp.td $(testlib_temp_srcs)

# time
testlib_time_srcs= \
	$(STDLIB)/time/$(PLATFORM)/functions.ha \
	$(STDLIB)/time/$(PLATFORM)/$(ARCH).ha \
	$(STDLIB)/time/types.ha

$(TESTCACHE)/time/time.ssa: $(testlib_time_srcs) $(testlib_rt) $(testlib_linux_vdso)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/time
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ntime \
		-t$(TESTCACHE)/time/time.td $(testlib_time_srcs)

# types
testlib_types_srcs= \
	$(STDLIB)/types/limits.ha \
	$(STDLIB)/types/classes.ha \
	$(STDLIB)/types/arch$(ARCH).ha

$(TESTCACHE)/types/types.ssa: $(testlib_types_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/types
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Ntypes \
		-t$(TESTCACHE)/types/types.td $(testlib_types_srcs)

# unicode
testlib_unicode_srcs= \
	$(STDLIB)/unicode/properties.ha \
	$(STDLIB)/unicode/unicode.ha

$(TESTCACHE)/unicode/unicode.ssa: $(testlib_unicode_srcs) $(testlib_rt)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/unicode
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nunicode \
		-t$(TESTCACHE)/unicode/unicode.td $(testlib_unicode_srcs)

# unix::passwd
testlib_unix_passwd_srcs= \
	$(STDLIB)/unix/passwd/passwd.ha

$(TESTCACHE)/unix/passwd/unix_passwd.ssa: $(testlib_unix_passwd_srcs) $(testlib_rt) $(testlib_bufio) $(testlib_io) $(testlib_os) $(testlib_strconv) $(testlib_strings)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/unix/passwd
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nunix::passwd \
		-t$(TESTCACHE)/unix/passwd/unix_passwd.td $(testlib_unix_passwd_srcs)

# uuid
testlib_uuid_srcs= \
	$(STDLIB)/uuid/uuid.ha

$(TESTCACHE)/uuid/uuid.ssa: $(testlib_uuid_srcs) $(testlib_rt) $(testlib_crypto_random) $(testlib_strio) $(testlib_fmt) $(testlib_endian) $(testlib_io) $(testlib_bytes)
	@printf 'HAREC \t$@\n'
	@mkdir -p $(TESTCACHE)/uuid
	@HARECACHE=$(TESTCACHE) $(HAREC) $(TESTHAREFLAGS) -o $@ -Nuuid \
		-t$(TESTCACHE)/uuid/uuid.td $(testlib_uuid_srcs)

