image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
  - scdoc
sources:
- git://c9x.me/qbe.git
- https://git.sr.ht/~sircmpwn/harec
- https://git.sr.ht/~sircmpwn/hare
triggers:
- action: email
  condition: failure
  to: "<~sircmpwn/hare-dev@lists.sr.ht>"
tasks:
- environment: |
    cd hare
    if [ "$BUILD_SUBMITTER" = "git.sr.ht" ]
    then
      if [ "$GIT_REF" != "refs/heads/master" ]
      then
          complete-build
      fi
      if [ "$(git remote get-url origin)" != "https://git.sr.ht/~sircmpwn/hare" ]
      then
        complete-build
      fi
    fi
- signoff: |
    cd hare
    if [ "$BUILD_REASON" = "patchset" ]
    then
        if ! git log --format='%b' origin/master^^.. | grep 'Signed-off-by' >/dev/null
        then
            echo "Patch missing Signed-off-by"
            exit 1
        fi
    fi
- qbe: |
    cd qbe
    make -j2 PREFIX=/usr
    sudo make install PREFIX=/usr
- harec: |
    cd harec
    cp configs/linux.mk config.mk
    make -j2
    sudo make install
- hare: |
    cd hare
    cp configs/linux.mk config.mk
    make -j2
    sudo make install
- check: |
    cd hare
    make -j2 check
- check_with_libc: |
    cd hare
    hare test -lc
- parsechk: |
    cd hare
    hare run cmd/parsechk
- lint: |
    cd hare
    ./scripts/lint.sh
- bootstrap: |
    cd hare
    make -j2 bootstrap
    if [ -n "$(git status --porcelain)" ]
    then
        echo "bootstrap makefiles out of date, run make bootstrap to regenerate"
        exit 1
    fi
- genoiddb: |
    cd hare
    hare run cmd/genoiddb < encoding/asn1/stdoid/db.txt > encoding/asn1/stdoid/db.ha
    if [ -n "$(git status --porcelain)" ]
    then
        echo "Either encoding/asn1/stdoid/db.ha is out of date or something broke genoiddb"
        exit 1
    fi
- docs: |
    cd hare
    make docs/html
    tar -C docs/html -cvz . > docs.tar.gz
    if [ $BUILD_SUBMITTER != "git.sr.ht" ]
    then
        echo "Not uploading docs for non-git.sr.ht build"
        exit
    fi
    acurl -f https://pages.sr.ht/publish/docs.harelang.org -Fcontent=@docs.tar.gz || true
