image: openbsd/latest
sources:
- https://git.sr.ht/~sircmpwn/hare
- https://git.sr.ht/~sircmpwn/harec
- git://c9x.me/qbe.git
packages:
- binutils
- scdoc
- git
triggers:
- action: email
  condition: failure
  to: "<~sircmpwn/hare-dev@lists.sr.ht>"
tasks:
- environment: |
    cd hare
    if [ "$BUILD_SUBMITTER" = "git.sr.ht" ]
    then
      if [ "$GIT_REF" != "refs/heads/master" ]
      then
          complete-build
      fi
      if [ "$(git remote get-url origin)" != "https://git.sr.ht/~sircmpwn/hare" ]
      then
        complete-build
      fi
    fi
- qbe: |
    cd qbe
    make -j2 PREFIX=/usr
    doas make install PREFIX=/usr
- harec: |
    cd harec
    cp configs/openbsd.mk config.mk
    make -j2
    doas make install
- hare: |
    cd hare
    cp configs/openbsd.mk config.mk
    make -j2
    doas make install
# remove once openbsd-7.5 is out. leap-seconds.list was after 7.4
- leapseconds: |
    cd /usr/share/zoneinfo
    doas ftp https://data.iana.org/time-zones/tzdb/leap-seconds.list
- check: |
    cd hare
    make -j2 check
