#!/bin/sh
# Yes, I am entirely aware that this is a hack
srcdir="$(dirname "$0")"
getmods() (
	DOCS=1
	. $srcdir/gen-stdlib
	IFS="
"
	for module in $modules; do
		if [ -z "$(echo "$module" | cut -sf1)" ]
		then
			echo "$module"
		else
			module="$(echo "$module" | cut -sf1)"
			echo $module
		fi
	done
)
modules="$(getmods)"

mkdir -p docs/html/

if ! [ -f docs/html/mascot.jpg ]
then
	curl https://harelang.org/mascot.jpg > docs/html/mascot.jpg
fi

haredoc -Fhtml > docs/html/index.html
for mod in $modules compress format encoding math crypto hare rt iobus
do
	echo $mod
	path="$(echo $mod | sed -e 's?::?/?g')"
	mkdir -p docs/html/$path
	haredoc -Fhtml $mod >docs/html/$path/index.html
done
