#!/bin/sh
# Yes, I am entirely aware that this is a hack
modules=$(awk '
/^modules="/ { sub(/.*=\"/, ""); gsub(/_/, "::"); print $1; mods = 1 }
/^[a-z][a-z0-9_]+$/ { if (mods == 1) { gsub(/_/, "::"); print $1 } }
/^[a-z][a-z0-9_]+"$/ { if (mods == 1) { mods = 0; sub(/"/, ""); gsub(/_/, "::"); print $1 } }
' < scripts/gen-stdlib)

mkdir -p docs/html/

curl https://harelang.org/mascot.jpg > docs/html/mascot.jpg
haredoc -Fhtml > docs/html/index.html
for mod in $modules compress format encoding math crypto hare rt
do
	path="$(echo $mod | sed -e 's?::?/?g')"
	mkdir -p docs/html/$path
	haredoc -Fhtml $mod >docs/html/$path/index.html
done
