#!/bin/sh
set -e

lookup() {
	for i in "$1"/*
	do
		i="${i#./}"
		[ -d "$i" ] || continue
		case "$i" in
			.*|*+*|cmd|contrib|docs|scripts)
				continue
				;;
			*)
				for j in "$i"/*.ha
				do
					[ -e "$j" ] || break
					i="$(printf '%s\n' "${i%/}" | sed 's|/|::|g')"
					printf 'use %s;\n' "$i"
					break
				done
				lookup "$i"
				;;
		esac
	done
}

lookup .
