#!/bin/sh
# Prints the default build tags for the host
case $(uname) in
	Linux)
		platform="linux"
		;;
	FreeBSD)
		platform="freebsd"
		;;
	*)
		printf "Warning: unknown target %s\n" "$(uname)" >&2
		platform="unknown"
		;;
esac

printf "%s\n" "$platform"
